HandyBus/handybus-web-latest

- .github/CODEOWNERS
- .github/auto_assign.yml
PR의  Reviewer과 Assignees가 자동으로 할당되도록 하였습니다.
auto_assign 파일을 추가했습니다.
> chore: auto-assign 파일 추가

- src/components/AskHandyButton.tsx
- src/icons/chevron-right.svg
"핸디에게 물어보기" 버튼을 추가했습니다.
* `chevron-right.svg`를 추가했습니다.
* `AskHandyButton.tsx`를 추가했습니다.
> feat(디자인시스템): ask-handy-button

- src/components/Button.tsx
버튼을 Figma에 맞게 수정했습니다.
어떤 변경 사항이 있나요?
* `Button`의 size가 명확하게 지정되어 있지 않던 문제를 수정했습니다. (`w-full`, `h-44`)
> design(디자인시스템): button

- src/data/regions.json
지역 정보를 관리하기 위한 sub branch를 생성하고, 최초 데이터를 등록했습니다.
관련 논의 내용은 노션에서 `회의록`>`10/29 지역 데이터 처리 관련 (dev team)`을 참고해주세요.
어떤 변경 사항이 있나요?
`regions.json`을 추가했습니다.
> init(지역): region data

- src/components/Tabs.stories.tsx
- src/components/Tabs.tsx
디자인 시스템 중 탭 컴포넌트를 추가했습니다.
어떤 변경 사항이 있나요?
* items를 받는 `Tabs` 컴포넌트를 만들었습니다. `items, selected, onSelected` prop을 받습니다.
```typescript
const items = [
{ value: 10, label: '예약 내역' },
{ value: 20, label: '수요 확인 내역' },
{ value: 30, label: '지난 콘서트' },
];
const [selected, setSelected] = useState<number>(30);
return <Tabs items={items} selected={selected} onSelect={setSelected} />;
```
> feat(디자인시스템): tabs

- src/components/Tabs.stories.tsx
- src/components/Tabs.tsx
- 탭의 폰트 굵기가 디자인과 다르던 문제를 해결
- 탭 storybook 경미한 수정
어떤 변경 사항이 있나요?
탭의 폰트 굵기(`font-600`)가 적용되지 않아 디자인과 다르던 문제를 해결했습니다.
> design(디자인시스템): tabs

- src/components/Section.tsx
홈 페이지를 개발하는 중 반복적으로 사용되는 디자인시스템을 발견하였고, 다른 페이지에서도 자주 쓰이는 것 같아 추가했습니다.
* `Section` 컴포넌트를 추가했습니다.
From Figma:
Created:
> feat(디자인시스템): section

- src/components/modals/CustomModal.tsx
- src/components/modals/confirm/ConfirmModal.tsx
- src/components/modals/handy-request/HandyRequestModal.stories.tsx
- src/components/modals/handy-request/HandyRequestModal.tsx
- src/components/modals/select/SelectModal.tsx
모달의 위치가 올바르지 않고, 데드존과 같이 보여지던 이슈 해결
어떤 변경 사항이 있나요?
- deadzone z-[99] 에 맞춰 모달의 z-index를 맞춤.
- Select 모달에서 4개까지의 노선만 보여지도록 반영
> fix(디자인시스템): 모달이 제대로된 위치에 보여지지 않고 데드존도 함께 보여지는 이슈, Select Modal 의 최대 노선 4개 제한

- src/app/globals.css
어떤 변경 사항이 있나요?
폰트 굵기가 Figma와 다르게 보이는 문제를 해결하기 위해 렌더링 옵션을 추가하는 수정을 했습니다.
> design(디자인): 폰트 굵기 문제 해결

- src/components/buttons/button/Button.tsx
클릭시 시각적 효과를 주기위해 색상을 좀 더 밝게 주었습니다.
https://github.com/user-attachments/assets/df3f301a-f923-4e12-88dc-c62be1ba5828
> design(디자인시스템): alert 타입 버튼 클릭시 색상 추가

- src/components/buttons/icon-button/IconButton.tsx
icon 버튼의 추가 style 속성을 지정할 수 있게 className Props를 추가하였습니다.
className 으로 tailwind-css 형식에 맞게 스타일 속성 추가하시면 됩니다.
> fix(디자인시스템): icon button의 style 추가 반영할 수 있게 변경

- .github/workflows/deploy.yml
- appspec.yml
배포 관련 설정들을 추가했습니다.
- 배포 cicd 파일들을 추가했습니다.
> chore: 배포 cicd action 추가

- .github/workflows/deploy.yml
- appspec.yml
> chore: 배포 action 노드 버전 수정

- .github/workflows/deploy.yml
- appspec.yml
> chore: deploy action 노드 버전 수정

- .github/workflows/deploy.yml
- appspec.yml
> chore: 배포 빌드 경로 수정

- .github/workflows/deploy.yml
> chore: 배포 zip 파일 이름 수정

- .github/workflows/deploy.yml
> chore: 배포 action에서 s3 파일 접근 경로 수정

- .github/workflows/deploy.yml
- appspec.yml
- deploy.sh
- ecosystem.config.js
- package.json
> chore: pm2 설정 파일 추가

- src/components/bottom-sheet/BottomSheet.tsx
바텀시트의 description 프로퍼티를 추가하였습니다.
> fix(디자인시스템): bottom sheet description 

- appspec.yml
- deploy.sh
> fix: 배포 이후 pm2 재실행 로직 구현

- src/app/api/[...path]/route.ts
- src/services/config.ts
안전한 방식으로 url 조작하도록 변경했습니다.
`+` 연산자 대신 `new URL()`을 사용하도록 변경했습니다.
> hotfix: 안전한 방식으로 url 조작하도록 변경

- .github/workflows/pr-title-check.yml
어떤 변경 사항이 있나요?
`.env`가 적절히 노출되도록 수정했습니다.
> fix: 깃 액션 env 노출 설정 추가

- src/app/(home)/@demand/page.tsx
- src/app/api/[...path]/route.ts
올바르지 않은 Link 태그의 href로 인해 토큰 쿠키가 없어지는 현상을 해결했습니다.
> hotfix: 올바르지 않은 href 처리

- src/constants/token.ts
토큰 쿠키 옵션을 strict에서 lax로 변경했습니다.
> hotfix: 토큰 쿠키 옵션 lax로 변경

- src/constants/token.ts
> hotfix: 쿠키 토큰 secure 옵션 수정

- src/app/mypage/page.tsx
- src/types/client.types.ts
서버에서 변경된 유저 타입에 맞추어 타입을 변경하고, 해당 값을 사용하는 부분들을 같이 변경해주었습니다.
> hotfix: 서버에서 변경된 유저 타입에 맞추어 타입 변경

- .gitignore
- src/middleware.ts
배포주소에서 RSC 요청으로 인한 토큰 삭제를 방지해두었습니다.
> hotfix: rsc 요청으로 인한 토큰 삭제 방지

- src/middleware.ts
- src/services/auth.ts
- src/services/users.ts
- src/utils/parseProgress.ts
Vercel의 Edge Middleware는 Edge Runtime 환경에서 실행되기에, Node.js의 일부 기능에 의존하는 axios가 정상적으로 동작하지 않습니다.
이를 해결하기 위해 미들웨어에서 부르는 api 요청을 모두 fetch로 변경하였습니다.
> fix: 미들웨어에서 axios 대신 fetch를 사용하도록 변경

- src/app/(home)/layout.tsx
어떤 변경 사항이 있나요?
홈 화면에서 수요 조사 중 셔틀/예약 모집 중 셔틀의 순서가 바뀌어 배치되어있던 문제를 해결했습니다.
> fix(홈): 홈 화면 레이아웃 수정

- src/app/shuttle/util/fetch.util.ts
올바르지 않은 authInstance를 instance로 변경했습니다.
> hotfix: 올바르지 않은 auth instance 사용 수정

- .github/workflows/pr-title-check.yml
- package-lock.json
- package.json
- src/app/onboarding/@funnel/components/bottom-sheets/MarketingBottomSheet.tsx
- src/app/onboarding/@funnel/components/bottom-sheets/PersonalInfoBottomSheet.tsx
- src/app/onboarding/@funnel/components/bottom-sheets/ServiceBottomSheet.tsx
- src/app/shuttle-detail/components/BottomBar.tsx
최근 pr title checker의 문제가 생긴 건 아래 두 가지 문제가 모두 발생하여 생긴 것입니다:
1. 최신 `@types/react`에서 리액트 타이핑 관련 문제가 생겼고 (
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/71363 )
2. action에서 다른 패키지 매니저를 쓰다보니까 lockfile이 사실상 액션에서 무용지물이라 버전 설정한게 적용이 안 되어서 더 문제가 되었던 것 같네요. 
어떤 변경 사항이 있나요?
문제가 없는 버전으로 (lockfile을) 고정하고 액션에서 npm을 쓰도록 했습니다.
(pnpm을 쓰고 싶으시면 저희 로컬에서도 pnpm을 쓰도록 설정하는 것으로 해야해요.)
> hotfix: type check

- src/components/footer/Footer.tsx
푸터에 통신판매신고번호와 카카오톡 문의하기 버튼을 추가하였습니다.
> feat: 카카오톡 문의하기 통신판매업신고번호 추가

- src/components/shuttle-detail/ShuttleDetailPage.tsx
- src/components/shuttle-detail/components/BackButton.tsx
> fix: 불필요한 상단 공백 제거

- package-lock.json
- package.json
- src/app/auth/login/[oauth]/page.tsx
Oauth를 진행하는 페이지에 로딩 아이콘을 추가하고, 새로고침 시에 경고 메시지가 뜨도록 했습니다.
> fix(로그인): 소셜 로그인 로딩 아이콘 추가 및 새로고침 방지

- src/app/mypage/shuttle/components/DemandCard.tsx
- src/app/mypage/shuttle/components/tabs/DemandTab.tsx
- src/services/config.ts
- src/services/shuttleOperation.ts
수요조사 취소를 모달창으로 확인하도록 수정했습니다.
https://github.com/user-attachments/assets/3f760476-94ca-4324-8ccf-3c301b5bb11f
> fix(마이페이지-셔틀): 수요조사 취소하기를 모달창으로 확인

- src/app/mypage/shuttle/components/tabs/DemandTab.tsx
- src/components/modals/select/SelectModal.tsx
- src/components/shuttle-detail/components/ShuttleDemandStatus.tsx
- src/components/shuttle-detail/components/ShuttleForm.tsx
api 변경 대응 및 테스트 과정에서 발생한 문제를 해결했습니다.
> hotfix: api 변경 대응

- src/app/mypage/shuttle/components/tabs/DemandTab.tsx
마이페이지 셔틀의 수요 신청 현황 탭에서 예약이 진행 중인 항목들이 정상적으로 보이도록 수정했습니다.
> fix: 예약이 진행 중인 셔틀이 정상적으로 보이도록 수정

- .github/workflows/pr-checker.yml
> chore: relase pr title 추가

- src/app/mypage/shuttle/page.tsx
> hotfix: 셔틀 탭 초기 값 추가

- src/services/config.ts
fetch에 캐시 revalidate time을 60초로 설정했습니다.
> hotfix: fetch에 revalidate time 추가

- src/services/config.ts
fetch revalidate time을 단축시켰습니다.
> hotfix: fetch revalidate time 수정

- src/app/(home)/@shuttle/page.tsx
- src/app/shuttle/components/SubPage.tsx
- src/app/shuttle/page.tsx
- src/app/shuttle/util/fetch.util.ts
- src/app/shuttle/util/sort.util.ts
- src/utils/region.util.ts
어떤 변경 사항이 있나요?
* 셔틀 조회 api 에서 필터를 제대로 주지 못하던 문제를 해결했습니다.
* 셔틀 조회 api 가 이미 관련 지역 셔틀을 포함하여 주고 있는 점을 참고해 로직을 수정했습니다.
> fix: 셔틀 api 수정

- src/app/demand/[id]/write/components/WriteForm.tsx
- src/app/demand/[id]/write/components/writeForm.type.tsx
- src/app/demand/[id]/write/components/writeForm.util.ts
- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
- src/app/mypage/shuttle/[id]/page.tsx
- src/app/mypage/shuttle/components/DemandCard.tsx
- src/app/mypage/shuttle/components/ReservationCard.tsx
- src/app/shuttle/[id]/write/page.tsx
- src/app/shuttle/util/contain.util.ts
- src/components/shuttle/shuttle-route-visualizer/ShuttleRouteCard.tsx
- src/components/shuttle/shuttle-route-visualizer/ShuttleRouteTimeLocation.tsx
- src/components/shuttle/shuttle-route-visualizer/ShuttleRouteVisualizer.tsx
- src/services/reservation.ts
- src/types/client.types.ts
- src/types/shuttle.types.ts
예약 상세 페이지에서 탑승지 변경을 구현했습니다.
또한 api 변경사항에 따라 hub id 속성 이름들을 모두 변경했습니다.
> feat: 예약 탑승지 변경

- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
- src/app/mypage/shuttle/[id]/page.tsx
예약 상세 페이지에서 핸디 지원 및 취소를 구현했습니다.
> feat: 핸디 지원 및 취소 구현

- src/app/mypage/shuttle/[id]/page.tsx
- src/app/mypage/shuttle/[id]/refund/page.tsx
- src/app/mypage/shuttle/components/ReservationCard.tsx
- src/services/reservation.ts
> chore: 결제 관련 주석 해제

- src/app/mypage/profile/page.tsx
- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/onboarding/@funnel/components/OnboardingFunnel.tsx
- src/app/onboarding/@funnel/page.tsx
- src/types/client.types.ts
- src/utils/common.ts
소셜 로그인에서 전화번호를 가져왔을 시에 전화번호를 입력하는 온보딩 스텝을 스킵하도록 수정했습니다.
또한 마이페이지에서 전화번호를 확인할 수 있도록 했습니다.
> fix: 온보딩 시 전화번호가 존재할 경우 처리

- src/components/shuttle/shuttle-route-visualizer/ShuttleRouteTimeLocation.tsx
> design(공통컴포넌트): shuttle route visualizer 글자 정렬 조정

- src/app/mypage/coupons/components/Coupon.tsx
- src/app/mypage/coupons/components/CouponList.tsx
- src/app/mypage/coupons/components/RegisterCoupon.tsx
- src/app/mypage/coupons/page.tsx
- src/components/inputs/text-input/TextInput.tsx
- src/services/coupon.ts
- src/types/client.types.ts
내 쿠폰함 페이지에서 쿠폰 등록 및 조회 api를 연동했습니다.
https://github.com/user-attachments/assets/62fa3c23-8eef-4cb1-bc05-99b8ce3d5fd9
> feat(마이페이지): 쿠폰 생성 및 조회 api 연동

- src/app/actions/logout.action.ts
- src/app/auth/login/[oauth]/page.tsx
- src/app/onboarding/@funnel/components/OnboardingFunnel.tsx
- src/app/onboarding/@funnel/page.tsx
- src/app/onboarding/@top/page.tsx
- src/constants/token.ts
- src/middleware.ts
- src/services/users.ts
- src/utils/handleToken.ts
기존에 middleware에서 항상 api를 통해 온보딩 여부를 확인하던 부분을 쿠키로 대체하여 불필요한 api 요청을 없앴습니다.
> refactor: 온보딩 여부를 쿠키로 관리

- src/app/mypage/profile/edit/components/EditForm.tsx
- src/services/coupon.ts
- src/services/demand.ts
- src/services/reservation.ts
- src/services/reviews.ts
- src/services/users.ts
query invalidate가 페이지가 전환될 때 정상적으로 동작하도록 수정했습니다.
> fix: query invalidate가 정상적으로 동작하도록 수정

- src/app/mypage/shuttle/components/ReservationCard.tsx
- src/components/dead-zone/DeadZonePopup.tsx
- src/types/client.types.ts
데드존 팝업 및 예약 카드 href를 올바르게 수정했습니다.
> chore: href 수정

- src/components/notice-section/NoticeSection.tsx
취소 및 환불 유의사항 테이블 디자인을 일부 수정했습니다.
> design: 테이블 디자인 수정

- src/app/mypage/shuttle/[id]/page.tsx
핸디 승인 여부를 배차가 완료된 이후에 보여주도록 수정했습니다.
> fix: 핸디 여부를 배차 확정 이후에 보여주도록 수정

- src/app/onboarding/@funnel/components/steps/ArtistStep.tsx
- src/components/onboarding-contents/ArtistContent.tsx
온보딩 폼 제출 시 선택된 아티스트가 초기화 되는 문제를 수정했습니다.
> fix: 온보딩 제출 시 선택된 아티스트가 초기화 되지 않도록 수정

- src/app/layout.tsx
- src/constants/metadata.ts
> fix: json ld 형식에 맞추어 수정

- src/app/shuttle/[id]/write/components/ShuttleWriteStep2.tsx
- src/app/shuttle/[id]/write/sections/TossPayments.tsx
항상 validation 체크 -> trigger(버튼 클릭시 체크 하는 방식)으로 변경되었습니다.
항상 validation 체크에서 계속 지속적으로 발생하는 리렌더링 이슈로 텍스트 인풋에 포커싱아웃되는 문제가 쉽게 해결되지 않네요.
우선 예약하기프로세스만 trigger 로 변경해보겠습니다.
> fix(예약하기): 예약하기 플로우 중 탑승객 정보 입력 페이지에서 validation 적용

- src/app/mypage/shuttle/[id]/components/sections/ShuttleInfoSection.tsx
- src/app/mypage/shuttle/[id]/handy/page.tsx
- src/app/mypage/shuttle/[id]/page.tsx
- src/constants/shuttleBus.ts
- src/services/shuttleOperation.ts
- src/types/client.types.ts
> feat: 핸디 오픈채팅링크 api 연동

- src/app/shuttle/[id]/write/components/ShuttleWriteStep2.tsx
- src/app/shuttle/[id]/write/sections/TossPayments.tsx
billing/reservation API
이전) 토스 페이먼츠 예약 페이지 들어오면 결제생성 api 를 호출하였습니다
현재) 결제하기 버튼을 눌러야 결제 생성 api를 호출합니다.
customerKey
각 userId 마다 고유하지만, 복잡한 키를 생성합니다.
> refactor(예약하기): billing reservation api 결제시 호출로 변경 및 customerkey 생성로직 변경

- src/middleware.ts
- src/services/config.ts
refresh token이 만료 시 로그아웃 되도록 수정했습니다.
> hotfix: refresh token 만료 시 로그아웃

- src/components/header/Header.tsx
구글 검색 결과 향상을 위해 메인 헤딩을 추가했습니다.
> chore: heading 추가

- src/app/shuttle/[id]/write/page.tsx
- src/app/shuttle/[id]/write/sections/ReservationShuttleInfo.tsx
예약상세(예약확인하기)에서 예약하기 페이지로 넘어오면 보이는 select에 일자와 노선의 기본값을 반영했습니다
> feat(예약하기): 일자, 노선 기본값 반영

- src/app/shuttle/[id]/write/components/ShuttleWriteStep3.tsx
- src/app/shuttle/[id]/write/components/ShuttleWriteStep4.tsx
- src/app/shuttle/[id]/write/sections/PassengerInfo.tsx
- src/app/shuttle/[id]/write/sections/TossPayments.tsx
탑승객의 인원을 늘렸다가 줄였다가 하는 상황에서 발생하는 빈폼이슈, 유령 인원 이슈 해결하였습니다.
> fix(예약하기): 탑승객 폼 인원 이슈 해결

- src/app/shuttle/[id]/write/page.tsx
예약하기에서 더이상 열려져 있지 않는 노선은 선택되지도, 보여지지도 않습니다.
> fix(예약하기): 예약하기에서 열려있는 노선만 반영

- src/app/shuttle/[id]/write/sections/TossPayments.tsx
- src/app/shuttle/[id]/write/sections/TotalPriceInfo.tsx
- src/app/shuttle/util/fetch.util.ts
- src/services/auth.ts
- src/services/common.ts
- src/services/coupon.ts
- src/services/demand.ts
- src/services/hub.ts
- src/services/reservation.ts
- src/services/reviews.ts
- src/services/shuttleOperation.ts
- src/services/users.ts
- src/utils/handleToken.ts
> fix: api version 추가

- src/app/shuttle/[id]/write/components/ShuttleWriteStep2.tsx
- src/app/shuttle/[id]/write/sections/PassengerForm.tsx
[예약하기 - 2step 탑승객 폼] 
- 입력이 불완전한 상태로 다음단계로 버튼을 누르면 넘어가지지 않는데, 폼에 해당하는 에러메시지가 뜨질않는 이슈 해결
- 승객 인원수가 2명 이상일때 첫번째 승객의 폼 이외의 폼에서 에러메시지가 뜨지 않는 이슈 해결
> fix(예약하기): 탑승객 폼에서 validation 이슈해결

- .github/workflows/pr-checker.yml
pr-title-checker의 이름을 pr-checker로 변경하였습니다.
> chore(github-action): change pr-title-check name to pr-checker

- src/app/shuttle/[id]/write/sections/TossPayments.tsx
API 버저닝에 맞춰서 v1 prefix를 추가하였습니다.
> refactor(예약하기): add v1 prefix in front of 결제승인

- src/app/demand/[id]/components/BottomBar.tsx
- src/app/demand/[id]/components/DemandForm.tsx
- src/app/demand/[id]/components/RouteModal.tsx
- src/app/mypage/shuttle/components/DemandCard.tsx
- src/app/mypage/shuttle/components/ReservationCard.tsx
- src/app/mypage/shuttle/components/tabs/DemandTab.tsx
- src/app/reservation/[id]/components/BottomBar.tsx
- src/app/reservation/[id]/components/PriceStats.tsx
- src/app/reservation/[id]/components/ReservationForm.tsx
- src/components/modals/select/SelectModal.tsx
- src/components/shuttle-detail/bottom-bar/BottomBar.tsx
- src/components/shuttle-detail/bottom-bar/ShareSheet.tsx
- src/constants/status.ts
- src/hooks/useShare.ts
- src/services/demand.ts
- src/types/client.types.ts
- src/types/hub.type.ts
- src/types/shuttle.types.ts
- src/utils/dateString.ts
수요조사 상세 페이지에서 선택한 날짜 및 지역에 대한 노선이 존재할 경우 모달이 표시되도록 구현했습니다.
> feat(수요조사 상세): 현재 예약을 받고 있는 노선이 있어요 모달 구현

- src/components/shuttle-detail/components/KakaoMap.tsx
fix(카카오맵): 지도 UI 렌더링 이슈 해결, 카카오맵 키 핸디버스 앱 키로 변경 #190 반영이후 local에서는 정상작동하는데 dev에서 렌더링되지않는 이슈가 발생했습니다. vercel env 반영도 제대로 되어있는데 문제점을 좁히기 위해서 테스트를 진행합니다.
변경사항 이전 코드로 롤백 및 새로운 env 만 적용
> test(카카오맵): 카카오맵 렌더링 테스트

- src/components/shuttle-detail/components/KakaoMap.tsx
> test(카카오맵): 이전 env key로 원상복구

- src/app/reservation/[id]/write/components/steps/payment-step/ApplyCoupon.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/ApplyHandy.tsx
> hotfix: 핸디 버튼 type 수정

- src/services/auth.service.ts
- src/types/auth.type.ts
> fix: 로컬 로그인 이슈 해결

- src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
- src/app/reservation/[id]/components/ReservationForm.tsx
- src/components/modals/handy-request/HandyRequestModal.tsx
- src/components/route-visualizer/RouteVisualizer.tsx
Route Visualizer 패딩 값을 수정 했습니다.
> design: route visualizer 패딩 수정

- src/app/auth/login/[oauth]/page.tsx
- src/app/demand/[id]/write/components/WriteForm.tsx
- src/app/mypage/shuttle/[id]/refund/page.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/ApplyCoupon.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/PaymentStep.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
- src/app/reservation/[id]/write/payments/page.tsx
- src/components/modals/confirm/ConfirmModal.tsx
수요조사, 예약, 환불 처리 중 제출 버튼이 비활성화 되도록 수정했습니다.
> fix: 폼 제출 도중 버튼 비활성화

- src/app/reservation/[id]/components/PriceStats.tsx
- src/app/reservation/[id]/page.tsx
- src/app/reservation/util/sort.util.ts
- src/components/bottom-sheet/share-sheet/ShareSheet.tsx
- src/constants/token.ts
- src/hooks/useShare.ts
- src/utils/config.util.ts
> design: 일부 디자인 수정

- src/app/auth/login/[oauth]/page.tsx
- src/app/reservation/[id]/write/payments/page.tsx
- src/hooks/useBottomSheet.tsx
- src/hooks/usePreventScroll.ts
> fix: 스크롤 방지 훅 구조 변경

- src/services/billing.service.ts
> hotfix: api 경로 수정

- src/app/(home)/@reservation/page.tsx
- src/app/demand/[id]/components/DemandStats.tsx
- src/app/login/page.tsx
- src/app/mypage/reviews/page.tsx
- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/mypage/shuttle/[id]/page.tsx
- src/app/onboarding/@funnel/components/bottom-sheets/ServiceBottomSheet.tsx
- src/app/reservation/[id]/components/PriceStats.tsx
- src/app/reservation/[id]/components/ReservationForm.tsx
- src/app/reservation/[id]/write/components/steps/PassengerInfoStep.tsx
- src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/ApplyHandy.tsx
- src/app/reservation/[id]/write/page.tsx
- src/app/reservation/[id]/write/payments/[reservationId]/page.tsx
- src/app/reservation/[id]/write/payments/fail/page.tsx
- src/app/reservation/components/ShuttleRouteView.tsx
- src/components/counter/Counter.tsx
- src/components/select/Select.tsx
- src/services/billing.service.ts
- src/services/user-management.service.ts
- src/types/shuttle-operation.type.ts
예악 상세 페이지 및 예약하기 페이지에서 잔여석과 가격이 표시되도록 수정했습니다.
> fix: 잔여석 및 가격 표시

- src/app/mypage/shuttle/[id]/components/sections/PaymentInfoSection.tsx
- src/app/reservation/[id]/components/ReservationForm.tsx
> fix: 좌석 수 계산 수정

- src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
쿠폰을 적용하였을 때 결제가 안되면 문제를 해결했습니다.
> fix: 쿠폰 적용 시 결제 안되던 문제 해결

- src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
> fix: 결제 로직 일부 수정

- src/components/buttons/back-button/BackButton.tsx
- src/types/shuttle-operation.type.ts
> design: 뒤로가기 버튼 배경 추가

- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
- src/app/mypage/shuttle/[id]/page.tsx
- src/components/chips/route-status-chip/RouteStatusChip.stories.tsx
- src/components/chips/route-status-chip/RouteStatusChip.tsx
- src/constants/status.ts
- src/types/shuttle-operation.type.ts
- src/types/user-management.type.ts
버스 배차 관련 정책에 맞추어 예약 상세에서 보여주는 값들이 올바르게 보여지도록 수정했습니다.
> fix(에약 상세): 버스 배차 관련 정책 변경에 맞추어 예약 상세에서 보여주는 값 변경

- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
- src/app/mypage/shuttle/[id]/page.tsx
- src/app/mypage/shuttle/components/tabs/DemandTab.tsx
예약 상세 페이지에서 버스 정보가 보이는 조건을 수정했습니다.
> fix: 버스 정보 표시 조건 수정

- src/app/(home)/@demand/page.tsx
- src/app/help/faq/page.tsx
- src/app/mypage/reviews/write/[id]/page.tsx
- src/components/buttons/redirect-button/RedirectButton.tsx
- src/services/shuttle-operation.service.ts
- src/types/shuttle-operation.type.ts
리뷰 작성의 post body를 api 형식에 맞추어 수정했습니다.
리뷰 작성 성공 시 내 리뷰 페이지로 리다이렉트 되도록 했습니다.
> fix(리뷰): 리뷰 작성 api 형식에 맞추어 수정

- src/services/shuttle-operation.service.ts
##개요
v2 마이그레이션 된 api 의 접미사가 v1으로 되어있는 단순 이슈였습니다.
> fix(마이페이지): 핸디가 오픈채팅방 제출 안되는 이슈 해결

- src/app/mypage/coupons/components/CouponList.tsx
- src/app/mypage/shuttle/components/tabs/CurrentTab.tsx
- src/app/mypage/shuttle/components/tabs/PastTab.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/CouponBottomSheet.tsx
- src/app/sitemap.ts
- src/services/user-management.service.ts
> fix: 쿠폰 조회 api 쿼리 수정

- src/components/modals/select/SelectModal.tsx
올바른 url path 를 주고있지 않아발생하는 에러였습니다
> fix(수요조사상세): 현재 예약을 받고있는 노선이 있어요에서 올바르지않은 페이지로 리디렉트 되던 에러

- src/app/reservation/[id]/write/components/steps/payment-step/ApplyCoupon.tsx
> fix: 쿠폰 할인 가격 계산 수정

- src/app/mypage/profile/page.tsx
- src/components/onboarding-contents/ArtistContent.tsx
최애 아티스트 선택 로직을 수정했습니다.
디테일한 디자인 사항은 머지된 이후 디자이너님에게 컨펌 받을 예정입니다.
https://github.com/user-attachments/assets/51d848fe-1c5a-411a-93a0-27bc4814bd0a
> fix: 최애 아티스트 선택 로직 수정

- src/app/mypage/leave/page.tsx
> fix: 회원 탈퇴 버튼 중복 클릭 방지

- src/app/sitemap.ts
queryParam의 &를 &amp; 로 작성하여 파싱에러를 해결하였습니다.
> fix: sitemap error

- src/app/demand/[id]/components/BottomBar.tsx
> fix: 수요조사 제출 버튼 오류 수정

- src/app/reservation/[id]/write/components/steps/payment-step/ApplyCoupon.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/ReservationInfo.tsx
> fix: 쿠폰 할인 계산식 수정

- src/app/auth/login/[oauth]/page.tsx
- src/app/login/page.tsx
- src/app/mypage/shuttle/[id]/refund/page.tsx
로그인 페이지에서 리다이렉트 url을 핸들링 로직을 session storage에서 쿠키로 관리하도록 변경했습니다.
> fix: 리다이렉트 로직 쿠키로 변경

- src/app/login/page.tsx
> fix: 리다이렉트 로직 수정

- src/app/auth/login/[oauth]/page.tsx
- src/app/login/page.tsx
리다이렉트 url이 로컬 스토리지에 저장되도록 수정했습니다.
> fix: 리다이렉트 url이 로컬 스토리지에 저장되도록 수정

- src/app/auth/login/[oauth]/page.tsx
- src/app/login/page.tsx
리다이렉트 url을 인코딩 및 디코딩하도록 수정했습니다.
> fix: 리다이렉트 url 인코딩 적용

- src/app/(home)/@modal/page.tsx
홈 안내 모달 문구 변경
더 나은 경험을 제공하기 위해 준비 중이에요. 예약이 가능한 기존 사이트로 이동합니다. 
-> 더 나은 경험을 제공하기 위해 준비 중이에요. 현재는 기존 사이트에서만 예약이 가능합니다.
> design: 홈 준비중 모달 description 수정

- src/app/(home)/@modal/page.tsx
배포된 production, preview 도메인 둘 다에서 node_env 로 접근하면 production 으로 인지합니다.
때문에 이를 구분하기 위해서 vercel_env를 사용하기전에 테스트를 진행합니다.
> test: node env 대신 vercel env 사용

- src/services/shuttle-operation.service.ts
- src/types/common.type.ts
어떤 변경 사항이 있나요?
cursor기반 pagination된 api가 더 이상 number가 아니게 된 api 변경 사항을 반영했습니다.
> fix: pagination api

- .github/auto_assign.yml
> chore: pr auto assign 유저 수정

- src/app/(home)/@modal/page.tsx
- src/app/auth/login/[oauth]/page.tsx
- src/app/login/page.tsx
- src/app/mypage/shuttle/[id]/refund/page.tsx
Reverts HandyBus/handybus-web-latest#247
> Revert "release"

- src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
토스 페이먼츠 위젯의 렌더링을 기다리도록 수정했습니다.
> fix: 토스 페이먼츠 위젯 렌더링 기다리도록 수정

- src/app/mypage/shuttle/[id]/page.tsx
핸디 선정 시 버스 배차 중 공지가 안 보이도록 수정했습니다.
> fix: 핸디 선정 시 배차 중 공지 숨김

- src/services/shuttle-operation.service.ts
> fix: 페이지네이션 api 반영

- public/icons/baseline-minus.svg
- public/icons/baseline-plus.svg
- src/app/mypage/shuttle/[id]/components/sections/HandySection.tsx
- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/mypage/shuttle/[id]/page.tsx
- src/app/mypage/shuttle/components/ReservationCard.tsx
- src/app/reservation/[id]/write/components/Form.tsx
- src/app/reservation/[id]/write/components/steps/PassengerInfoStep.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/ApplyCoupon.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/ReservationInfo.tsx
- src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
- src/components/counter/Counter.tsx
- src/types/billing.type.ts
- src/types/user-management.type.ts
> fix: 개별 탑승객 정보 입력 삭제

- src/app/demand/[id]/components/BottomBar.tsx
- src/app/mypage/shuttle/[id]/components/sections/HandySection.tsx
- src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
- src/app/reservation/[id]/components/BottomBar.tsx
- src/services/shuttle-operation.service.ts
핸디 오픈채팅 링크 제출 페이지로 리다이렉트 되는 버튼의 링크를 올바르게 수정했습니다.
> fix: 핸디 오픈채팅링크 제출 페이지 리다이렉트 링크 수정

- public/icons/toasty-check.svg
- src/app/demand/[id]/components/BottomBar.tsx
- src/app/demand/[id]/components/DemandForm.tsx
- src/components/toast-container/ToastContainer.css
- src/components/toast-container/ToastContainer.tsx
수요조사 페이지의 제출하기 버튼 클릭 시 하단으로 스크롤 되도록 하였습니다.
폼이 화면 상에 존재할 시에는 알맞은 에러 토스트가 띄워집니다.
https://github.com/user-attachments/assets/047a64d6-cbe8-46f1-885d-2f43864a3b28
> feat: 수요조사 페이지 CTA 상시 활성화, 클릭 시 하단 스크롤링

- .github/workflows/pr-checker.yml
- commitlint.config.js
더이상 제목에 대문자가 오더라도 실패하지 않습니다.
Pull Request 제목에 release 가 오더라도 실패하지 않습니다.
> fix: 커밋린트, pr checker 규칙 완화

- .github/workflows/assign_reviewer.yml
- src/types/user-management.type.ts
> chore: 리뷰어 자동 배정 액션 추가

- src/app/mypage/profile/page.tsx
- src/app/onboarding/@funnel/components/OnboardingFunnel.tsx
- src/app/onboarding/@funnel/components/steps/PersonalInfoStep.tsx
- src/app/onboarding/@funnel/components/steps/PhoneNumberStep.tsx
- src/app/onboarding/@funnel/components/steps/ProfileInfoStep.tsx
- src/app/onboarding/@funnel/components/steps/ResidenceStep.tsx
온보딩과 프로필에서 최애 아티스트를 선택 및 수정 하던 로직을 주석 처리 해두었습니다.
> fix: 최애 아티스트 선택 주석 처리

- src/app/(home)/@modal/page.tsx
- src/app/mypage/shuttle/components/DemandCard.tsx
- src/app/mypage/shuttle/components/ReservationCard.tsx
- src/app/reservation/[id]/components/ReservationForm.tsx
- src/app/reservation/[id]/write/payments/[reservationId]/page.tsx
- src/components/select/Select.tsx
- src/utils/localStorage.ts
예약 완료 후 띄워지던 피드백 모달을 로컬스토리지로 관리하여 홈에서 띄워지도록 했습니다.
> fix: 예약 완료 후 피드백 모달을 로컬스토리지로 관리

- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
- src/app/mypage/shuttle/[id]/handy/page.tsx
- src/app/mypage/shuttle/components/ReservationCard.tsx
- src/components/modals/handy-request/HandyRequestModal.tsx
핸디 페이지에 처음 접근했을 때 예약 상세 페이지로 리다이렉트 되던 문제를 해결했습니다.
예약 상세에서 탑승시간 및 행사 일자 관련 로직 및 워딩을 수정했습니다.
> fix: 핸디 페이지 리다이렉트 수정

- src/app/(home)/@modal/page.tsx
> chore: 서비스 준비 중 모달 삭제

- src/components/notice-section/NoticeSection.tsx
정확한 탑승일은 예약 상세에서 확인할 수 있습니다. 라는 문구를 추가하였습니다
> style: 환불 안내 문구 수정

- src/app/demand/[id]/page.tsx
- src/app/demand/page.tsx
- src/app/error.tsx
- src/app/help/layout.tsx
- src/app/mypage/shuttle/[id]/layout.tsx
- src/app/not-found.tsx
- src/app/policy/page.tsx
- src/app/reservation/[id]/page.tsx
- src/app/reservation/page.tsx
> design: 홈에서만 푸터를 보여주도록 변경

- src/app/demand/[id]/components/BottomBar.tsx
- src/app/demand/[id]/components/DemandForm.tsx
- src/app/demand/[id]/write/components/RouteInfo.tsx
- src/app/demand/[id]/write/components/WriteForm.tsx
- src/app/reservation/[id]/components/ReservationForm.tsx
수요조사와 예약하기 바텀시트에 남아있던 운행일 용어를 일자로 변경하였습니다.
> style: 운행일에서 일자로 용어 변경

- src/types/shuttle-operation.type.ts
> chore: event 타입 수정

- src/app/(home)/@top/components/PromotionBanner.tsx
- src/app/demand/page.tsx
- src/constants/demand.ts
> chore: 배너 href 수정

- src/app/onboarding/components/OnboardingFunnel.tsx
온보딩 이후에 로그인 쿠키가 설정되지 않던 이슈를 해결했습니다.
> fix: 온보딩 이후 로그인 쿠키가 설정 안되는 문제 해결

- src/app/mypage/profile/edit/components/EditForm.tsx
- src/app/mypage/reviews/write/[id]/page.tsx
- src/app/onboarding/components/OnboardingFunnel.tsx
- src/services/core.service.ts
- auth 를 사용하는 core presigned url api 로 변경하였습니다.
- common.service.ts 를 core.service.ts 로 파일 이름을 변경하였습니다.
> refactor: core presigned url api 반영

- src/app/demand/[id]/components/DemandStats.tsx
단순히 오는편<->가는편의 값이 반대로 들어가있었습니다
> fix: 수요조사 카운트 오는편 가는편 바꿔서 보여지는 이슈

- src/app/help/about/components/AboutMerit.tsx
- src/app/help/about/components/AboutService.tsx
- src/app/help/about/components/AboutStats.tsx
- src/app/help/about/components/EndSection.tsx
- src/app/help/about/components/TopSection.tsx
- src/app/help/about/page.tsx
- src/app/help/how-to/page.tsx
> design: 서비스 소개, 이용절차 페이지 업데이트

- src/app/(home)/@top/components/PromotionBanner.tsx
- src/app/(home)/@top/page.tsx
- src/app/auth/login/[oauth]/page.tsx
- src/services/core.service.ts
- src/types/user-management.type.ts
전화번호 미등록 계정으로 회원가입 시 에러 토스트가 띄워지도록 처리했습니다.
> feat: 전화번호 미등록 계정 회원가입 처리

- src/app/(home)/@demand/page.tsx
- src/app/(home)/@reservation/components/RoutesSwiperView.tsx
- src/app/(home)/@reservation/page.tsx
- src/app/demand/components/DemandFilterContainer.tsx
- src/app/demand/page.tsx
- src/app/demand/utils/param.util.ts
- src/app/demand/utils/toSorted.util.ts
- src/app/reservation/components/Empty.tsx
- src/app/reservation/page.tsx
- src/components/article/Article.stories.tsx
- src/constants/demand.ts
셔틀 요청 버튼 이동 및 타이틀과 필터의 텍스트를 일부 수정했습니다.
> fix: 셔틀 요청 버튼 이동 및 텍스트 일부 수정

- src/app/(home)/@top/components/PromotionBanner.tsx
- 3초마다 자동으로 넘어갑니다.
- loop 가 적용되서, 목록의 끝에 도달해도 처음으로 돌아갑니다.
- 마우스 호버시 멈춥니다.
> feat: 배너 auto play, loop 및 호버시 멈춤 적용

- src/app/demand/utils/toSorted.util.ts
- src/app/help/reviews/components/DetailedReview.tsx
- src/app/mypage/shuttle/[id]/components/sections/RefundInfoSection.tsx
- src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
- src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
- src/app/mypage/shuttle/[id]/page.tsx
- src/app/mypage/shuttle/components/ReservationCard.tsx
- src/app/reservation/[id]/components/PriceStats.tsx
- src/app/reservation/util/sort.util.ts
- src/components/coupon/Coupon.tsx
- src/types/shuttle-operation.type.ts
- src/types/user-management.type.ts
- src/utils/dateString.util.ts
- src/utils/dayjsTz.util.ts
기존에 자바스크립트 Date를 사용하던 부분으로 인해 서버에서 렌더링 시 시간대가 맞지 않는 문제가 있었습니다.
이를 해결하기 위해 모든 부분에서 Dayjs를 사용하도록 변경했습니다.
> fix: Date를 Dayjs로 통일

- src/app/(home)/@top/components/PromotionBanner.tsx
realindex: loop 모드에서 실제 index 를 사용하여 인덱스 표기가 깨지던 에러를 해결하였습니다.
https://github.com/user-attachments/assets/47269c3c-6cd0-450b-bdb3-4e8dfeaaba02
> fix: 배너 인덱스 표기 오류 해결

- src/app/auth/login/[oauth]/page.tsx
- src/app/mypage/profile/edit/components/EditForm.tsx
- src/app/onboarding/components/OnboardingFunnel.tsx
- src/app/onboarding/components/steps/AgreementStep.tsx
- src/app/onboarding/components/steps/PersonalInfoStep.tsx
- src/app/onboarding/page.tsx
- src/components/onboarding-contents/PersonalInfoContent.tsx
- src/components/onboarding-contents/formValidation.constants.ts
- src/components/onboarding-contents/onboarding.types.ts
- src/services/config.ts
- src/types/user-management.type.ts
기존 유저의 progress가 더 이상 배열이 아닌 별개의 속성으로 오는 사항을 반영했습니다.
#341 PR을 먼저 머지해야합니다.
> fix: 유저 progress 변경사항 대응

- src/app/reservation/[id]/components/BottomBar.tsx
- src/app/reservation/[id]/components/ReservationForm.tsx
- src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx
노선의 예약 마감 및 좌석 마감 상태에 따라 하단 버튼의 텍스트가 다르게 보이도록 수정했습니다.
> fix: 노선의 마감 상태에 따라 버튼 상태 변경

- src/app/reservation/[id]/write/payments/fail/page.tsx
잔액 부족 등 402 에러시 적절한 화면을 보여주지 않던 에러를 고쳤습니다.
> fix: 402 결제 에러

- src/app/mypage/shuttle/utils/refund.util.ts
마이페이지에서 오는 편 탑승시간 계산식을 수정했습니다.
> fix: 마이페이지 탑승시간 계산식 수정

- src/app/reservation/[id]/write/payments/fail/page.tsx
- src/app/reservation/[id]/write/payments/page.tsx
이전 pr 에서 state와 useEffect로 페이지가 마운트 되었을때 searchParams 를 가져오도록 반영하였습니다
> fix: development 환경에서 searchparams 가 인식되지 않는 이슈 대응

- src/services/config.ts
> hotfix: 토큰 업데이트 로직 수정

- src/components/select/Select.tsx
Select의 바텀시트에서 스크롤이 안되던 문제를 수정했습니다
> fix: select 바텀시트 스크롤

- .github/workflows/pr-labeler.yml
자동으로 pr 의 라벨을 달아주는 pr labeler 작동 테스트 중 입니다.
> test: pr labeler 동작 테스트

- .github/workflows/pr-labeler.yml
인식하지 못하는 주석을 제거하였습니다.
어떤 변경 사항이 있나요?
- 관련 스크린샷
> fix: pr-labeler 에러해결

- .github/workflows/pr-labeler.yml
> test: 이모지 없는 라벨 테스트

- src/services/hub.service.ts
백엔드 api 버전업 릴리즈에 따라 location/regions/regionId/hubs v2 api를 적용합니다.
> release: v1

- src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
결제 페이지에서 이용약관을 미동의 시에도 자리 선점이 되던 이슈를 수정했습니다.
> fix: 결제 약관 미동의 시 에러 처리

- src/app/mypage/reviews/write/[id]/page.tsx
- src/app/mypage/shuttle/components/tabs/PastTab.tsx
- 리뷰 작성 시 1000자 제한을 두었습니다
- 취소된 예약들에 대해 후기 작성하기 버튼을 비활성화 하였습니다.
> feat: 리뷰 글자 수 제한

- src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
토스 약관의 동의 여부 기본 값을 변경한 사항을 대응했습니다.
> hotfix: 토스 결제 약관 동의 기본 값 변경 대응

- src/services/config.ts
204 에서 response body를 기대하여 에러를 던지는 이슈를 해결하였습니다.
authInstance에서 204 의 경우를 별도로 처리해주었습니다. 
> fix: 204 에서 response body를 기대하여 에러를 던지는 이슈 해결

- src/services/config.ts
config애서 204 status code에 대한 no content를 대응하도록 수정했습니다.
> hotfix: config에서 204 status code 대응

- src/app/mypage/components/Settings.tsx
- src/app/mypage/notice-board/[id]/page.tsx
- src/app/mypage/notice-board/components/NoticeItem.tsx
- src/app/mypage/notice-board/components/NoticeList.tsx
- src/app/mypage/notice-board/page.tsx
https://github.com/user-attachments/assets/78554a32-e713-40f3-a96e-42c3439cc68d
> feat: 공지사항 마크업

- src/app/(home)/@event/components/EventsSwiperView.tsx
캐러셀을 넘길 때 가끔씩 사라지는 버그를 해결했습니다.
> fix: 캐러셀 렌더링 버그 수정

- src/app/event/[eventId]/components/demand-complete-screen/DemandCompleteScreen.tsx
- src/app/event/[eventId]/components/demand-complete-screen/FailScreen.tsx
- src/app/event/[eventId]/components/demand-complete-screen/SuccessScreen.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/fail/page.tsx
- src/app/help/faq/page.tsx
- src/components/feedback/FeedbackScreen.tsx
- src/services/core.service.ts
> feat: 의견 보내기 api 연동

- src/app/mypage/alert-requests/components/AlertRequestCard.tsx
> feat: 내 빈자리 알림 요청 내역에서 순서 표시

- src/services/hub.service.ts
event destination을 event location으로 변경하는 api 명세에 따라 대응했습니다.
> fix: event destination을 event location으로 변경

- src/app/event/[eventId]/components/event-form/EventForm.tsx
- src/app/event/[eventId]/components/event-form/hooks/useAlertFeedBackScreen.tsx
- src/app/event/[eventId]/components/event-form/hooks/useBottomSheetText.tsx
- src/app/event/[eventId]/components/event-form/hooks/useEventInitialization.tsx
- src/app/event/[eventId]/components/event-form/hooks/useHistory.tsx
- src/app/event/[eventId]/components/event-form/hooks/useInputSectionText.tsx
- src/app/event/[eventId]/components/steps/StepComponent.tsx
- src/app/event/[eventId]/page.tsx
행사 상세 페이지 내 로직들을 분리하여 가독성 향상 및 책임의 분리를 적용했습니다.
> refactor: 행사 상세 페이지 로직 분리

- src/components/notice-section/NoticeSection.tsx
택시팟 협업이 시작됨에 따라 변경된 예약 유의사항을 반영했습니다.
https://github.com/user-attachments/assets/c714bd36-3d20-4b21-82d5-16d9ddc78a21
> fix: 예약 유의사항 업데이트

- src/components/notice-section/NoticeSection.tsx
추가 요청된 예약 유의사항에 핸디팟 예약 마감일 문구가 추가되었습니다.
> design: 예약 유의사항에 핸디팟 예약마감일 문구 추가

- src/app/(home)/@event/components/CardSection.tsx
- src/app/(home)/@event/components/ViewAllButton.tsx
- src/app/event/components/Empty.tsx
- src/app/event/components/Error.tsx
- src/app/event/components/Loading.tsx
- src/app/event/page.tsx
- src/components/article/Article.tsx
홈 UI 피드백을 반영하였습니다.
- 추천행사 섹션
- 전체보기 '>' 아이콘 굵게
- 전체보기 동그란 아이콘 옅게
- 홈 전체보기 
- 하단 여백 추가
> design: 홈 UI 피드백을 반영

- src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
> fix: 핸디 가이드 링크 수정

- src/app/mypage/reviews/components/WritableReviews.tsx
- src/app/mypage/reviews/components/WrittenReviews.tsx
내 후기 작성가능한 후기 / 작성한 후기 에서 취소된 예약을 보여주던 버그를 수정하였습니다.
- 내 예약조회 -> 예약 상태 : COMPLETE_PAYMENT && 셔틀 노선 상태 : ENDED 일때 리스트에 표기해줍니다.
- 작성가능한 후기 : reviewId가 없을 때
- 작성한 후기 : reviewId가 있을 때
- 남아있던 작성한 후기 컴포넌트에서 evnet progress = PAST 를 제거하였습니다.
> fix: 내 후기에서 취소된 예약을 보여주던 이슈 해결

- src/app/(home)/@bot/components/PromotionReviews.tsx
- src/app/mypage/reviews/[reviewId]/components/ReviewItem.tsx
- src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx
- src/app/reviews/components/ReviewItem.tsx
- src/app/reviews/components/ReviewList.tsx
- src/hooks/useInfiniteScroll.tsx
리뷰 전체보기 모바일에서 무한스크롤 안되는 이슈 및 UI 개선
- 무한스크롤 안되는 이슈 해결
- 행사 명과 날짜를 한 줄로 표기
> fix: 리뷰 전체보기 모바일에서 무한스크롤 안되는 이슈 및 UI 개선

- src/app/event/[eventId]/components/event-form/components/BottomBar.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PriceSection.tsx
- src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
- src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/PriceSection.tsx
- src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/components/RegularPriceContent.tsx
NotificationBubble, CouponSection, 핸디지원금정보 부분에 UI 피드백 반영
커밋 참고
> design: UI 피드백 반영 (NotificationBubble, CouponSection, 핸디지원금정보)

- src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
- src/app/help/about/components/AboutService.tsx
- src/app/mypage/reviews/components/reservation-card/hooks/useEventText.ts
- src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useEventText.ts
> feat: 수요조사 정류장 태깅 적용

- src/app/event/page.tsx
행사 전체보기 페이지에서 판매대기 행사들을 필터링 했습니다.
> fix: 행사 전체보기에서 판매대기 행사들 필터링

- src/app/help/faq/page.tsx
- src/components/dead-zone/DeadZonePopup.tsx
- src/components/feedback/FeedbackScreen.tsx
기존에 데드존에 있던 의견 남기기 버튼이 노션 링크로 연결되던 부분을 피드백 화면이 띄워지도록 수정했습니다.
> feat: 데드존 의견 남기기 버튼을 내부 의견 남기기 화면으로 통일

- src/app/layout.tsx
- src/components/service-maintenance-screen/ServiceMaintenanceScreen.tsx
> feat: 점검중 표시 반영

- src/app/(home)/@event/components/RecommendedEventSwiperView.tsx
- src/app/(home)/@event/components/TrendEventsSwiperView.tsx
- src/app/(home)/@event/page.tsx
홈의 캐러셀에서 첫 진입 시에 숫자가 보이지 않던 버그를 수정했습니다.
현재 프로덕션 환경에서만 버그가 발생하여 병합 이후 추가적인 테스트를 할 예정입니다.
> fix: 첫 진입 시 캐러셀 숫자 미표시 버그 수정

- src/components/guidelines/contents/Notice.tsx
상품별 유의사항이 변경되었습니다.
| 변경전 | 변경후 |
|--------|--------|
| <img width="457" alt="Screenshot 2025-06-10 at 2 24 33 PM" src="https://github.com/user-attachments/assets/ec429578-deda-4387-9378-802cc5cec84b" /> | <img width="361" alt="Screenshot 2025-06-10 at 2 22 06 PM" src="https://github.com/user-attachments/assets/69ddef22-e5ef-4517-9a19-19415878c597" /> | 
> design: 상품별 유의사항 변경

- src/app/(home)/@event/components/RecommendedEventCard.tsx
> design: n월의 추천 행사에서 이달의 추천 행사로 명칭 변경

- src/components/card/Card.tsx
배포환경에서 가끔 카드의 숫자가 사라지는 이슈 해결
fixed -> absolute 로 변경해서 제대로 해결되는지 테스트 해봅니다...
> fix: 배포환경에서 가끔 카드의 숫자가 사라지는 이슈 해결

- src/app/mypage/alert-requests/components/AlertRequestCard.tsx
> fix: 빈자리 알림 취소

- src/app/event/[eventId]/components/steps/extra-steps/ExtraHubsInRouteStep.tsx
- src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
- src/components/buttons/button/Button.tsx
비활성화 버튼 디자인이 없던 variant들을 반영했습니다.
또한 행사 바텀시트 내에서 '전석 매진' 텍스트가 줄바꿈 되던 현상을 해결했습니다.
> fix: 버튼 비활성화 디자인 반영 및 텍스트 깨짐 현상 처리

- src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
- src/app/event/[eventId]/components/steps/components/SimpleRouteInfo.tsx
- src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
- src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
- src/app/event/[eventId]/components/steps/reservation-steps/ReservationTripTypeStep.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ShuttleRouteInfoSection.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/page.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/payment.const.ts
- src/app/event/[eventId]/store/dailyEventIdsWithHubsAtom.ts
- src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
- src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx
- src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/HubItem.tsx
- src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/TripCard.tsx
- src/components/tab/Tabs.tsx
- src/types/shuttleRoute.type.ts
- src/utils/event.util.ts
- src/utils/taxiRoute.util.ts
완전 편도 노선이 올바르게 대응되도록 수정했습니다.
특정 방향이 없을 경우 중복 노선 단계에서 해당 방향 숨김 처리 및 가격 미표시 등을 진행했습니다.
그 외에 핸디팟 노선에 대하여 시간이 일부 페이지들에서 여전히 보이던 부분들을 같이 처리했습니다. 다만 시간이 없을 경우 어색하게 보이는 디자인들이 일부 있어 보여서 보람님 돌아오시면 한번 같이 확인해보면 좋을 것 같아요.
> feat: 완전 편도 노선 대응

- src/app/event/[eventId]/components/event-form/EventForm.tsx
- src/app/event/[eventId]/components/steps/StepComponent.tsx
- src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
- src/hooks/analytics/useDemandTracking.tsx
- src/utils/analytics/demandAnalytics.util.ts
수요조사 플로우 GA에서 초기 입장이 안되던 부분 추가 및 세부적인 로직들을 수정했습니다.
> fix: 수요조사 GA 플로우 수정

- src/app/event/[eventId]/components/handy-party/components/steps/AddressStep.tsx
- src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
- src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
피드백에 따라 가이드 문구 디자인을 일부 수정했습니다.
> design: 핸디팟 가이드 문구 디자인 일부 수정

- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
- src/types/coupon.type.ts
특정 행사에서만 사용 가능한 쿠폰의 경우 결제 단계에서 해당 행사일 경우에만 보여지도록 수정했습니다.
내일 보람님 돌아오시면 더 적합한 디자인을 적용할 예정입니다.
> feat: 특정 행사에만 사용 가능한 쿠폰 반영

- src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
- src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
- src/app/event/[eventId]/components/steps/reservation-steps/ReservationTripTypeStep.tsx
남은 좌석 수가 5석보다 많을 시에는 여유로 보이도록 수정했습니다.
> feat: 남은 좌석 수 숨김 처리

- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/icons/radio-disabled.svg
- src/components/coupon/Coupon.tsx
- src/services/coupon.service.ts
- src/services/event.service.ts
특정 행사에서만 사용 가능한 쿠폰의 디자인을 반영했습니다.
> design: 특정 행사에서 사용 가능한 쿠폰 디자인 반영

- src/app/(home)/@top/components/AnnouncementBanner.tsx
- src/app/(home)/@top/page.tsx
홈에서 중요한 공지를 상단에 표시할 수 있는 곳을 만들었습니다.
> feat: 공지사항 배너

- src/app/(home)/@top/page.tsx
> chore: 상단 중요 공지 비활성화

- src/app/(home)/@bot/components/PromotionReviews.tsx
- src/app/(home)/@greeting/page.tsx
- src/app/event/[eventId]/components/event-form/EventForm.tsx
- src/app/event/[eventId]/components/steps/StepComponent.tsx
- src/app/event/[eventId]/components/steps/extra-steps/ExtraRealNameInputStep.tsx
- src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ClientInfoSection.tsx
- src/app/event/[eventId]/form.const.tsx
- src/app/event/[eventId]/form.type.ts
- src/app/mypage/components/Profile.tsx
- src/app/mypage/page.tsx
- src/app/mypage/profile/edit/components/EditForm.tsx
- src/app/mypage/reviews/[reviewId]/components/ReviewItem.tsx
- src/app/reviews/components/ReviewItem.tsx
- src/components/header/Header.tsx
- src/components/header/UserProfile.tsx
- src/components/onboarding-contents/ProfileInfoContent.tsx
- src/components/onboarding-contents/formValidation.const.ts
- src/components/onboarding-contents/onboarding.type.ts
- src/types/review.type.ts
- src/types/user.type.ts
- src/utils/generateProfileBackgroundColor.ts
프로덕트 내에 실명제가 도입됩니다.
- 기존유저를 포함한 이름을 받지 않은 유저들은 예약하기 직전 실명 이름을 입력하여야 합니다.
- 마이페이지에서 닉네임 -> 이름 변경 반영
- 글자 프로필 이미지에서도 이름을 기준으로 보여집니다.
- 후기에서 이름이 블러처리되어 보여집니다. 예) 임**, 닉네임은 그대로 보여집니다. 예) 팔란티어좋아
- 예약 페이지에서 닉네임이 아닌 실명을 보여줍니다. 하지만 실명검증을 하지 않기때문에 가명을 쓸 사람도 충분히 생길 수 있습니다.
- 한글 혹은 영어 (띄어쓰기 포함) 2자 ~ 20자 이내
- 가능한 예시) William Bradley Pitt, 박흥모
- 불가능 예시) 박흥모ㅁ, 샤넌 그레이, Shanen 안녕, 4번안타류현진 등
- 후기에서 탈퇴한 유저는 '탈퇴한 유저'라고 이름이 보여집니다.
| 프로필 수정 |
|-----------|
|<img width="421" height="507" alt="Screenshot 2025-07-30 at 2 55 47 PM" src="https://github.com/user-attachments/assets/18a290a5-14ba-4496-89a5-b4ac9d586a04" />|
| 홈페이지 후기 | 후기 페이지 |
|--------|--------|
| <img width="444" height="775" alt="Screenshot 2025-07-30 at 3 28 35 PM" src="https://github.com/user-attachments/assets/0411b6a9-ba05-47af-b600-6ec7f6509f …
> feat: 실명제 도입

- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
- src/app/mypage/boarding-pass/hooks/useBoardingPassData.ts
- src/app/mypage/boarding-pass/page.tsx
- 탑승권에 인원, 이름, 전화번호를 표기합니다
- 데이터 검증로직이 훅이 추가되었습니다.
- 정류장의 index 가 아닌 sequence 를 사용합니다.
- 결제페이지 쿠폰 리스트 스크롤추가
> fix: 탑승인원 표기 및 데이터 검증 로직 추가, 결제페이지 쿠폰 리스트 스크롤

- src/app/event/[eventId]/components/EventOverview.tsx
> design: 데이식스 전용 상세페이지 적용

- .cursor/mcp.json
- .cursor/rules/sentry.mdc
- next.config.mjs
- package-lock.json
- package.json
- sentry.edge.config.ts
- sentry.server.config.ts
- src/app/error.tsx
- src/app/layout.tsx
- src/instrumentation-client.ts
- src/instrumentation.ts
Sentry를 도입합니다. 실시간으로 유저 환경에서 에러 모니터링이 가능합니다.
catch하지못하는 error 를 모두 집계합니다. 반대로 우리가 원하는 에러를 sentry가 집계하도록 커스텀 할 수도 있습니다. (추후 어떤 상황에서 어떤 에러를 집계하도록 할지 연구 필요)
url : https://handybus-kw.sentry.io/insights/projects/handybus-web/?project=4509874464817152
ID : handybus google 계정
- try, catch 문으로 처리하지 않은 에러 발생시 sentry issue에 집계됨.
- 최초 발생시각, 최근 발생시각, 발생한 에러 이벤트 수, 유저 수
- 발생 url
- Stack Trace
- 유저 replay 제공 (미쳤음, 월 50개까지) 
- Hydration Error Diff
- Breadcrumbs
- HTTP Request
- Tag
- Contexts (User 국적, 브라우저 환경, 운영체제, 디바이스 등)
- slack 을 통한 알림
- email 을 통한 개발팀 각자에게 알림 (핸디버스 계정 외 개발자 계정을 핸디버스 팀에 등록해야함. 팀 요금제 필요)
-> 주기적으로 에러 대시보드를 확인하는 수 밖에...
- 14일이 지난 데이터 확인
- Error Monitoring : 5k errors
- Tracing : 10M spans
- Session Replay : 50 replays
https://sentry.io/pricing/
- cursor rule (sentry) 로 프롬프트에서 해당 rule …
> feat: 유저 에러 모니터링 툴 (Sentry) 설치

- package-lock.json
- src/app/mypage/settings/page.tsx
> design: 애플 로그인 배지

- src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
복수 노선 뷰에서 가는 편의 경우 도착 시간을 표시하도록 수정했습니다.
> feat: 복수 노선 뷰에서 가는편의 경우 도착 시간 표시

- src/app/layout.tsx
- src/components/service-maintenance-screen/ServiceMaintenanceScreen.tsx
> chore: 서버 점검 적용

- src/app/layout.tsx
> chore: 서버 점검 해제

- package-lock.json
- package.json
- src/app/mypage/profile/edit/components/EditForm.tsx
- src/app/mypage/reviews/write/[reservationId]/components/ReviewWriteForm.tsx
- src/app/mypage/reviews/write/[reservationId]/page.tsx
리뷰 및 프로필 이미지 업로드 시 크기를 압축하여 업로드 되도록 하였습니다.
- 프로필 이미지: 0.3 MB
- 리뷰 이미지: 0.7MB
> feat: 리뷰 및 프로필 사진 업로드 시 크기 압축

- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
- src/app/mypage/boarding-pass/hooks/useBoardingPassData.ts
- src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
세븐틴 행사에 한해서 임시로
각 노선별 오픈챗 링크를 공지방 참여 버튼에 연결합니다.
> feat: 세븐틴 임시 노선별 오픈채팅방링크 연결

- src/app/help/handybus-guide/page.tsx
> design: 핸디버스 가이드 문구 추가

- src/app/received-reservation/[token]/page.tsx
- src/services/reservationTransferRequest.service.ts
- src/types/reservation.type.ts
- src/types/reservationTransferRequest.type.ts
예약 양도 알림톡에서 연결되는 페이지 내의 승인 기능을 구현했습니다.
현재 테스트를 위해 기초 로직만 연결해놓은 상태이며, 디자인은 앱 디자인이 나온 뒤에 적용될 예정입니다.
> feat: 예약 양도 승인하기 페이지 기초 구현

- src/utils/event.util.ts
특정 케이스에 대하여 올바르게 계산되지 않던 결제 금액을 수정했습니다.
> fix: 결제 금액 계산 로직 수정

- src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PaymentSection.tsx
기존에 결제 유의사항 미확인 시 CTA 버튼을 비활성화 하던 방식에서, 활성화를 시키되 에러 토스트 표시 및 스크롤 되도록 변경하였습니다.
> feat: 결제 유의사항 미확인 시 에러 토스트 및 스크롤

- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/GuidelineSection.tsx
- src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/page.tsx
- src/components/script/TossPaymentsScript.tsx
- src/hooks/useTossPayments.tsx
- src/types/coupon.type.ts
기존에 결제 페이지 첫 진입 시 일부 상황에 대하여 토스 위젯이 로드되지 않던 상황을 해결하였습니다.
그 외에 결제 유의 사항 바텀시트 내에서 스크롤 위치가 올바르게 보여지지 않던 케이스를 해결했습니다.
> fix: 토스 페이먼츠 스크립트 로드 안정화
