.github/workflows/pr-title-check.yml
pr status check 에서 기존의 규칙(영어 소문자로시작) 에 한글 글자 허용을 하였습니다.
한글이 pr 제목에 들어갈 경우 fail 되던 이슈 해결
=> init(프론트 초기설정): status check rule에 시작문자 한글 허용

appspec.yml, deploy.sh
ec2 instance에서 pm2를 중복 실행하던 로직을 제거했습니다.
=> fix: pm2 중복 실행 제거

src/middleware.ts, src/services/auth.ts, src/services/config.ts, src/utils/handleSession.ts
로그아웃 이후에도 next에서 캐싱한 마이페이지를 통해 접근 가능했던 문제를 해결했습니다.
handleLogout 함수에 `/mypage`를 revalidate하는 함수를 추가하여 캐시를 초기화해주었습니다.
=> fix(로그인): 로그아웃 이후에도 마이페이지 캐싱을 통해 접근 가능했던 문제 해결

src/components/shuttle/shuttle-route-visualizer/ShuttleRouteVisualizer.stories.tsx, src/components/shuttle/shuttle-route-visualizer/ShuttleRouteVisualizer.tsx, src/types/shuttle.types.ts
예약  페이지 및 마이페이지(셔틀) 에서 사용될 노선 비주얼라이저 블러 이펙트 업데이트 입니다
Props는 아래와 같이 사용할 수 있어요. section을 `RESERVATION_DETAIL`(예약하기) 과 `MY_RESERVATION` (마이페이지-셔틀)두면 주요 `승탑지, 출발지, 도착지`를 제외하고는 블러처리됩니다.
출발지 방향 일땐 `is_pickup` 을, 도착지 방향일땐 `is_dropoff` 를 true 로 두고 사용하세요
```
object: [
{ time: '2024-03-20 14:30:00', location: '청주터미널' },
{ time: '2024-03-20 14:40:00', location: '청주대학교', is_pickup: true },
{ time: '2024-03-20 14:50:00', location: '장소3' },
{ time: '2024-03-20 15:00:00', location: '장소4' },
{ time: '2024-03-20 15:10:00', location: '장소5' },
{ time: '2024-03-20 15:20:00', location: '장소6', is_dropoff: true },
],
section: SECTION.RESERVATION_DETAIL,
```
=> feat: shuttle visualizer blur effect 업데이트

src/app/mypage/reviews/write/[id]/page.tsx, src/app/mypage/shuttle/[id]/page.tsx, src/app/mypage/shuttle/[id]/refund/page.tsx, src/app/mypage/shuttle/components/DemandCard.tsx, src/app/mypage/shuttle/components/ReservationCard.tsx, src/app/mypage/shuttle/components/tabs/CurrentTab.tsx, src/app/mypage/shuttle/components/tabs/DemandTab.tsx, src/app/mypage/shuttle/components/tabs/PastTab.tsx, src/app/mypage/shuttle/constants/shuttle.constants.ts, src/app/mypage/shuttle/page.tsx, src/services/shuttleOperation.ts, src/types/client.types.ts
마이페이지 - 셔틀 페이지를 구현 및 api을 연결했습니다.
마이페이지에서 유저가 신청한 수요조사 및 예약 내역을 확인할 수 있는 탭들을 구현했습니다.
- 유저별 예약 및 수요조사 생성을 아직 할 수 없어서 테스트를 해보지 못했습니다. 추후 어드민 페이지가 완성되면 테스팅하도록 하겠습니다.
- 예약 관련 페이지(예약 상세 페이지, 핸디 지원 페이지, 환불 내역 페이지)들의 기획이 변경되며 규모가 커져서 추후에 다른 PR로 올리도록 하겠습니다.
=> feat(마이페이지): 마이페이지 - 셔틀 구현

src/app/help/what-is-handy/page.tsx, src/app/mypage/shuttle/[id]/handy/page.tsx, src/app/mypage/shuttle/[id]/page.tsx, src/app/mypage/shuttle/components/DemandCard.tsx, src/app/mypage/shuttle/components/ReservationCard.tsx, src/app/mypage/shuttle/components/Section.tsx, src/components/modals/handy-request/HandyRequestModal.tsx, src/types/client.types.ts
예약 상세보기 페이지의 변경사항들을 마크업만 구현해두었습니다.
현재 각 상황에 따른 케이스들을 분리하지 않고 모두 넣어둔 상황입니다. 추후에 api를 연결하면서 케이스에 맞게 분리할 예정입니다.
핸디 가이드 페이지 마크업을 구현했습니다.
https://github.com/user-attachments/assets/0dabf474-37af-415b-a557-3f149c2aff34
=> feat(마이페이지-셔틀): 예약 상세보기 및 핸디 가이드 페이지 마크업

src/middleware.ts
미들웨어에서 request를 보냈을 때 access token이 만료된 경우 토큰을 업데이트 하는 핸들링 로직을 추가했습니다.
이로 기존에 invalid 한 access token 값을 가지고 인증이 필요한 페이지에 들어갔을 때 문제가 생기던 현상을 해결했습니다.
=> fix: 미들웨어에서 access token 만료 핸들링 로직 추가

src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx, src/app/shuttle/[id]/write/page.tsx, src/components/shuttle-detail/ShuttleDetailPage.tsx, src/components/shuttle/shuttle-route-visualizer/RoutePoint.tsx, src/components/shuttle/shuttle-route-visualizer/ShuttleRouteCard.tsx, src/components/shuttle/shuttle-route-visualizer/ShuttleRouteTimeLocation.tsx, src/components/shuttle/shuttle-route-visualizer/ShuttleRouteVisualizer.stories.tsx, src/components/shuttle/shuttle-route-visualizer/ShuttleRouteVisualizer.tsx, src/components/shuttle/shuttle-route-visualizer/shuttleRouteVisualizer.util.ts, src/types/shuttle.types.ts
type prop으로 `왕복행` / `콘서트행` / `귀가행` 노선을 보여줄 수 있습니다.
기존의 object prop대신 `toDestinationObject`, `fromDestinationObject` 를 사용합니다.
`{ arrivalTime, name, shuttleRouteHubId, sequence, selected? }[]` 형태로 넘겨주세요.
Section === MY_RESERVATION 일때 `selected` 된 승탑지는 기본값으로 선택되어있습니다
=> feat(공통컴포넌트): shuttle route visualizer api response type에 맞게 수정

src/hooks/useBottomSheet.tsx
바텀시트의 높이가 클 시 바텀시트가 올라오는 속도가 너무 빠른 문제를 해결하기 위해 높이별로 transform duration을 달리 했습니다.
=> fix: 바텀시트 높이에 따라서 transform duration 분리

src/app/mypage/coupons/components/CouponList.tsx
마이 페이지 쿠폰 필터에서 체크박스 부분이 안눌리는 문제를 해결했습니다.
=> fix: 쿠폰 체크박스가 안눌리는 문제 해결

src/components/bottom-sheet/BottomSheet.tsx, src/hooks/useBottomSheet.tsx, src/hooks/usePreventScroll.ts
기존에 바텀시트가 열렸을 때 뒷 배경이 스크롤 되던 문제를 해결했습니다.
=> fix: 바텀시트 열렸을 시 배경 스크롤 방지

src/app/shuttle/[id]/write/sections/PriceDetail.tsx, src/components/shuttle-detail/bottom-bar/BottomBarReservationRequest.tsx, src/components/shuttle-detail/bottom-bar/PriceInfo.tsx
예약하기 전 과정에서 가격에 쉼표로 3글자씩 구분지어지는 포맷팅을 적용했습니다.
=> fix(예약하기): 예약하기에서 가격 포맷팅

src/app/shuttle/[id]/write/sections/PriceDetail.tsx, src/app/shuttle/[id]/write/sections/TotalPriceInfo.tsx
- 쿠폰의 최대 적용인원이 1명으로 고정돼 잘못표기된 이슈 해결
- 예약하기 명당 가격이 얼리버드 일경우에도 일반 가격으로 표기되던 이슈 해결
=> fix(예약하기): 쿠폰 최대 적용인원이슈, 명당 가격표기 이슈 해결

src/app/shuttle/[id]/write/page.tsx
- 쿠폰등록시, 결제 취소 시 Toss Payments SDK UI 가 재렌더링되면서 발생하는 이슈입니다. toss payments sdk가 직접 dom 을 조작하면서 발생하는 이슈로 예상됩니다. 화면의 크기를 직접 지정하고 scoll-y 를 지정하는 방식으로 해결하였습니다.
=> fix: 토스페이먼츠 중 강제중단, 쿠폰 선택시 스크롤이 안되는 이슈

src/components/shuttle-detail/components/KakaoMap.tsx
지도 UI 렌더링 이슈 해결
- [문제원인] script로 제공되는 kakao map sdk를 사용하기 위해서 Next/Script를 사용하고 있습니다. `onLoad` 메서드를 사용하고있었는데, 이는 Script가 로드될때 onLoad 메서드로 제공되는 걸 함께 실행합니다. 이때문에 Script가 먼저 로드될 때 `window.kakao.maps` 가 준비되지 않았을 수 있습니다. 타이밍이 맞지 않으면 카카오맵 UI가 로드 되지 않는것이죠.
- [해결방법] `onReady` 메서드를 사용해서, 카카오맵 SDK가 완전히 준비되었을때 로드합니다.
카카오맵 키 환경변수 관련
- 기존의 사용하던 `NEXT_PUBLIC_KAKAO_MAP_APP_KEY`는 더이상 필요하지 않습니다. 각자 로컬에서 지워주셔도 됩니다. 기존 `NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY`를 함께 사용합니다.
=> fix(카카오맵): 지도 UI 렌더링 이슈 해결, 카카오맵 키 핸디버스 앱 키로 변경

src/components/kakao-map/KakaoMap.tsx
vercel env가 제대로 적용되지 않는 이슈로 인해서 테스트를 진행합니다.
NEXT_PUBLIC_KAKAO_MAP_APP_KEY(제 계정의 임시 키) -> NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY(핸디버스 계정의 공식키) 로 변경합니다
둘 다 모두 kakao develop API 키에서 javascript 키 입니다. 
=> test(카카오맵): 카카오맵 env key를 handybus 계정의 env key로 변경

src/app/layout.tsx, src/app/robots.ts, src/app/sitemap.ts, src/constants/metadata.ts, src/types/shuttle-operation.type.ts
metadata에 robots, viewport 를 추가하고, 기존의 twitter 프로퍼티를 제거하였습니다.
- twitter 프로퍼티가 없을때 twitter(x)는 openGraph 기존에 작성되었던 title, description, image 의 메타데이터를 가져옵니다. 
- viewport 는 모바일에서 검색엔진최적화와 관련되어있습니다 (아래 참고)
- robots 의 설정을 추가하였습니다.
ENV `production` 여부에 따라 sitemap 이 생성/비생성이 결정됩니다. dev domain의 경우 sitemap 이 등록되지 않기 위함.
sitemap 설정에서 `lastModified` 는 변경된 컨텐츠 내용을 반영해줘야합니다. 가장 좋은건 `event`, `shuttleRoute`가 생성 및 수정된 날짜를 동적으로 넣어주는 것입니다. 현재 api 스키마상에 관련 내용을 간단하게 가져올 수가 없어서 서버가 생성된 날짜로 들어가게 됩니다.
`/reservation/{shuttleRouteId}` 경로의 경우에는 현재 쿼리파람이 없을땐 페이지에러가 발생합니다. 이렇게 되면 크롤러가 올바르게 반영하지 못할 수 있습니다. 쿼리를 반영하자니, 서버사이드로 그려주는 페이지가 각각 다른 쿼리파람일때도 똑같은 내용의 컨텐츠만 그려줄것으로 예상되기에 오히려 검색엔진의 신뢰도 하락을 부를 수 있습니다. 
`domain-url/sitemap.xml` 로 접근하시면 생성된 라우팅경로를 모두 확인하실 수 있어요
다른 서비스들을 예로들어 보여드리자면 …
=> feat(SEO): robots, viewport, sitemap 설정 추가

src/app/demand/[id]/components/BottomBar.tsx, src/app/reservation/[id]/components/BottomBar.tsx, src/app/reservation/components/ShuttleRouteView.tsx, src/components/header/Header.tsx
앱바의 로그인 버튼을 로그인 여부에 따라 다른 버튼 디자인으로 보이도록 수정했습니다.
공유하기 버튼을 디자인 수정사항에 따라 더 가시성이 높은 디자인을 수정했습니다.
=> fix: 로그인 여부에 따라 로그인 버튼 다르게 표시 및 공유하기 버튼 디자인 수정

src/app/mypage/shuttle/components/ReservationCard.tsx, src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
토스 위젯이 렌더링 되는 도중 결제 버튼이 비활성화 되도록 했습니다.
=> fix: 토스 위젯 렌더링 중 결제 버튼 비활성화

src/app/(home)/@modal/page.tsx, src/app/(home)/layout.tsx, src/app/login/page.tsx, src/components/footer/Footer.tsx
- 디자이너님 요청사항을 반영했습니다.
- 홈에서 기존 서비스로 리디렉션되는 안내 모달 추가
- 로그인 페이지 디자인 색상 변경
- 푸터의 인스타 트위터 블로그 아이콘의 링크를 연결하였습니다.
=> feat: 디자이너 요청사항 반영(서비스 준비중 모달, 로그인 페이지 디자인) 및 qa사항 반영(푸터 아이콘 링크 연결)

src/app/(home)/@modal/page.tsx, src/components/modals/confirm/ConfirmModal.tsx
- confirm 모달에 다양한 variant options 추가 
- 홈의 서비스 준비중 모달에 primary variant 추가
=> fix: confirm 모달에 다양한 variant options 추가 및 홈의 서비스 준비중 모달에 primary variant 추가

src/app/(home)/@modal/page.tsx
개발환경에서는 홈에서 불필요한 서비스 준비중 안내 모달이 뜨지 않습니다.
=> fix: production 환경에서만 안내 모달 표시

src/app/mypage/shuttle/[id]/handy/page.tsx
버스 배정 상태에 따라 핸디의 오픈채팅링크 입력 폼이 활성화 되도록 했습니다.
=> fix: 버스 배정 상태에 따라 핸디 오픈채팅링크 제출 활성화

src/app/reservation/[id]/write/components/steps/PassengerInfoStep.tsx
예약하기에서 카카오톡 문의하기 링크가 빠져있던 문제를 해결하였습니다.
어떤 변경 사항이 있나요?
- 관련 스크린샷
=> fix(예약하기): 카카오톡문의하기 링크 추가

src/components/route-visualizer/RouteVisualizer.tsx
셔틀 예상 노선 -> 셔틀 노선으로 ShuttleVisulaizer 컴포넌트의 표시 이름이 변경되었습니다.
=> style: 컴포넌트 이름 변경

src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx, src/app/reservation/[id]/write/payments/fail/page.tsx, src/app/reservation/[id]/write/payments/page.tsx, src/utils/setTimeoutWithRetry.ts
: 토스페이먼츠 결제 후 결제중 페이지에서 **중지 혹은 새로고침**을 눌렀을때 문제가 야기될 수 있습니다. 
구체적인 예시로, 중지 버튼을 눌렀을때 `결제승인 API`(/v1/billing/payments/{paymentId} 이하 결제승인 API라고 부르겠습니다) response를 받지 않고 `cancled` 처리되어 fail url로 리디렉트되는 경우가 생길 수 있습니다. 그러나 화면에서 `결제 실패`라고 표기되나 결제승인 API는 완료되어서 `성공`했을 수 있음. 
```
참고. /v1/billing/payments/{paymentId} 의 케이스 별 응답 상태
첫시도 : 특이사항 없음. 정상적으로 응답 처리
앞선 요청 처리중, Request 재시도 : 앞의 api 결과 기다렸다가 전달
앞선 요청 처리완료, 5초 안에 재시도 : 앞선 api결과 
앞선 요청 처리완료, 5초 이후 재시도 : 다시 결제 승인 처리 -> 409, 이미 처리된 결제입니다 에러발생
```
: 추가로 해당유저(나)의 `reservation status`를 조회해서 `PAYMENT_COMPLETE` 일 경우 결제 성공 url로 리디렉션 처리됩니다. (duration 3000ms, max retry 3s 로 reservation status를 확인합니다)
(1) 중지 -> post payment API가 처리완료되면 polling으로 유저(나)의 reservation status를 추적해 자동으로 성공/실패 url로 리디렉션됨
(2) 새로고침 -> post payment 재요청 -> 성공/실패 url 로 리디렉션
(3) 5초 이상 …
=> fix(예약하기): 결제 실패이지만 예약완료일 수 있는 이슈 핸들링

src/app/demand/[id]/components/DemandForm.tsx, src/app/demand/[id]/components/DemandStats.tsx, src/app/demand/[id]/write/components/WriteForm.tsx, src/services/shuttle-operation.service.ts
- 이제 수요조사 페이지에 들어왔을때부터 일일행사의 모든 수요를 합쳐서 보여줍니다.
- 편도행 수요신청 안되던 버그가 고쳐졌습니다.
https://github.com/user-attachments/assets/dae1c376-4930-4ef6-ba66-82d5f7d3c89f
=> feat: 모든 행사일의 수요조사 반영 및 편도 수요조사 안되던 버그 해결

.github/workflows/pr-checker.yml
이전 vercel 을 사용하지 않을때 세팅해두었던 build test 를 제거합니다.
현재는 vercel 에서 빌드 테스트도 진행합니다.
이후 빌드 테스트가 제거되었기 때문에 PR-CHECKER의 검사 시간이 감소합니다.
=> chore: remove build test in PR-CHECKER

src/app/(home)/@demand/page.tsx, src/app/(home)/@reservation/page.tsx, src/app/(home)/layout.tsx, src/app/demand/page.tsx, src/app/demand/utils/toSorted.util.ts, src/app/reservation/constants/params.ts
- 지용님 요청에 의해 (보람님 검수 완) 홈의 카드들을 셔틀일자 빠른순으로 정렬하였습니다.
https://github.com/user-attachments/assets/52ccd5c9-c865-4bd4-a9db-82536233f835
로컬에서 빌드시에는 아무런 문제가 없으나, git hook으로 build 시에 에러가 발생함.
에러메세지는 `toSorted is not a function` 이었음.
**다음의 방법으로 해결 할 수 있었습니다.** 
저는 여기서 (2번) PR-CHECKER 에서 불필요한 18버전 빌드테스트를 지움으로서 해결했습니다.
1. 패러렐라우팅을 사용하는 페이지에서 `export const dynamic = 'force-dynamic'; ` 명시적으로 동적 렌더링 강제
2. nodejs 버전을 18v 보다 높게 설정한다.
**그런데 의문점이 생겼습니다.**
- toSorted 는 18v이하에서 지원하지 않음, 
- 현재 제 로컬 nodejs 버전과 vercel 배포환경 nodejs 버전은 모두 18v 보다 높아서 빌드시 에러가 발생하지 않았음.
- git hook 환경에서는 node version 이 18 버전이라 에러가 발생함.
엄밀한 원인 파악을 위해서 제 로컬 nodejs 버전을 18 버전으로 변경하고, 패러랠라우팅을 사용하는 페이지에 toSorted 를 사용했을때 빌드해보았는데요. 패러렐라우팅을 사용하는 페이지에서만 static site generating 에러가 발생했습니다. 
정말 이상한건 reservation/, demand/ 에서도 toSorted를 사용하는데 여기서는 …
=> feat: 홈의 수요조사/예약카드 셔틀일자 빠른순으로 정렬

src/app/(home)/@reservation/page.tsx
홈의 지금 예약 모집 중인 캐러셀을 SSR에서 CSR로 변경했습니다.
토큰 저장 로직이 쿠키에서 로컬 스토리지로 변경되면서 기존에 서버사이드에서 유저 정보를 기반으로 필터 값을 주던 캐러셀의 로직이 동작하지 않게 되었습니다. 따라서 토큰 로직과 맞추어 클라이언트 사이드에서 동작하도록 변경했습니다.
=> fix: 예약 모집 중 캐러셀을 CSR로 변경

src/app/mypage/shuttle/components/CancelBottomSheet.tsx
예약 취소 바텀시트의 약관 섹션에 높이 제한을 두어 하단 버튼이 안보이는 현상을 해결했습니다.
=> fix: 예약 취소 바텀시트 높이 제한

src/app/reservation/[id]/write/payments/fail/page.tsx, src/app/reservation/[id]/write/payments/page.tsx
결제 실패시 유저 측 사유로 발생하는 토스페이먼츠 실패 케이스를 핸들링하였습니다.
토스페이먼츠 에러 메세지를 보여줍니다.
보여지는 페이지의 구성은 다음과 같습니다
- 큰제목 : 결제 중 문제가 생겼습니다.
- 설명 : 잔액이 부족합니다 등 토스페이먼츠 에러메세지
참고.
(1) 409 완료된 예약 결제의 경우
- 큰 제목 :       이미 완료된 예약결제입니다.
- 설명 :    내 예약 페이지에서 확인해주세요.
(2) 이외 다른 결제 실패 페이지 구성 
- 큰 제목 : 결제 중 문제가 생겼습니다.
- 설명 : 마이페이지에서 결제 내역을 확인한 후 다시 시도해주세요.
=> feat: 결제실패시 toss error message 핸들링

src/app/reservation/[id]/page.tsx
예약 상세 페이지에서 지도의 위치가 잘못 들어가던 문제를 행사장으로 올바르게 변경했습니다.
=> fix: 예약 상세 페이지의 지도 위치 수정

src/app/mypage/profile/edit/components/EditForm.tsx, src/app/onboarding/components/OnboardingFunnel.tsx, src/app/onboarding/components/steps/AgreementStep.tsx, src/app/onboarding/components/steps/PersonalInfoStep.tsx, src/app/onboarding/page.tsx, src/components/onboarding-contents/PersonalInfoContent.tsx, src/components/onboarding-contents/formValidation.constants.ts, src/components/onboarding-contents/onboarding.types.ts
소셜 계정에서 성별 및 연령대 정보가 주어지지 않는 경우 온보딩 단계에서 정보를 수집할 수 있도록 수정했습니다.
=> fix: 소셜 로그인 시 정보가 오지 않는 경우 대응

src/services/config.ts, src/types/user-management.type.ts
토큰 갱신 로직에서 갱신 이후 retry 하는 api의 토큰을 갱신된 토큰을 사용하도록 변경했습니다.
=> fix: 갱신된 토큰을 retry 요청에서 사용하도록 수정

.github/workflows/pr-checker.yml
git action인 PR_CHECKER에서 release 만 사용해도 허용할 수 있게 합니다.
=> chore: release 예외처리

.github/workflows/pr-checker.yml
release label을 단 pr의 경우 checker가 사용하는 `action-semantic-pull-request@v5`를 무시하는 방법으로 시도해봅니다.
=> chore: ignore label about release

src/app/mypage/reviews/write/[id]/page.tsx
사진 첨부 기능이 개선되었습니다. 생각보다 간단히 개선할 수 있었어요.
**공통적인 사항**은 각 이미지 10MB까지, 최대 3장까지, 업로드한 이미지 삭제 가능입니다.
**개선된 사항**은 `사진 개별추가 기능`입니다. 
여태까지는 추가이미지를 업로드하면 기존의 이미지들이 모두 **대체**되어버립니다.
대체되지 않고, 올릴 수 있는 이미지 개수가 남아있다면, 추가되도록 반영했습니다.
https://github.com/user-attachments/assets/6b5c53be-9001-4a8a-b678-5bbff735f99d
https://github.com/user-attachments/assets/e8c6c6dd-741a-49eb-86b2-a660829b5397
=> feat(리뷰): 사진 첨부 기능 개선

src/app/reservation/[id]/write/components/steps/payment-step/ApplyHandy.tsx
- 결제 페이지에서 왕복을 선택해야만 핸디를 선택할 수 있습니다.
https://github.com/user-attachments/assets/7c30e186-f89b-4c7a-af89-aea98802428b
=> feat: 왕복행만 핸디를 선택할 수 있게 변경

src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx, src/components/select/Select.tsx
가는 편과 오는 편의 잔여석이 모두 존재하는 상태에는 추가 셔틀 요청하기 버튼이 숨김 처리 되도록 수정했습니다.
=> fix: 왕복 잔여석이 존재 시 추가 셔틀 요청하기 버튼 숨김 처리

src/app/(home)/@bot/components/Overviews.tsx, src/app/(home)/@bot/components/PromotionReviews.tsx, src/app/(home)/@demand/components/DemandView.tsx, src/app/(home)/@demand/page.tsx, src/app/(home)/@reservation/page.tsx, src/app/help/about/components/AboutMerit.tsx, src/app/help/about/components/AboutService.tsx, src/app/help/about/components/AboutStats.tsx, src/app/help/faq/page.tsx, src/app/help/how-to/page.tsx, src/components/article/Article.tsx
- 전체보기 버튼의 크기를 키워 가독성이 개선됩니다.
- 수요조사 캐러셀의 하단에 전체보기로 리디렉트하는 버튼을 배치하였습니다.
- 헤딩의 크기가 조정되었습니다.
- titleSize Prop 은 small | large -> string으로 변경되었습니다. Article을 사용하는 부분에서 전부 반영완료
=> feat: 홈페이지 전체보기 개선

src/app/mypage/shuttle/[id]/components/sections/HandySection.tsx, src/app/mypage/shuttle/[id]/page.tsx
왕복편을 선택하지 않은 예약건에 대해서 마이페이지에서 핸디지원이 불가능하도록 반영하였습니다.
- handyStatus 가 NOT_SUPPORTED 일때 ROUND_TRIP이 아니라면 NOT_QUALIFIED 라는 상태를 <HandySection /> 에 props로 넘겨줍니다.
- ROUND_TRIP이 아니라면 handyStatus와 상관없이 막아버릴 수도 있지만, 이미 편도행인데 핸디지원을 하셨던 유저분들도 존재하기도 하고, 기존의 유저들에게 영향을 주지 않고도 앞으로 편도행을 선택한 사람들에게만 핸디지원을 막아버릴 수 있는 방법을 사용했습니다.
- handyStatus, type(왕복/가는편/오는편) 에 따라 각각 기능 테스트를 모두 마쳤습니다.
=> feat: 마이페이지에서 핸디 지원 불가 처리 

src/components/header/Header.tsx
기존에 헤더에서 유저 정보를 무조건적으로 불러오기에 비로그인 상태로 헤더가 존재하는 페이지에 접속 시 홈으로 리다이렉트 되는 이슈가 있었습니다.
로그인 상태에서만 유저 정보를 불러오도록 수정하여 해결했습니다.
=> fix: 로그인 되었을 때에만 헤더에서 유저 정보를 불러오도록 수정

src/app/login/page.tsx
=> hotfix: login page coupon amount

src/app/reservation/[id]/write/components/steps/payment-step/ApplyHandy.tsx
CS 문의가 지속적으로 발생하고 있습니다.
그 내용은 핸디 지원자 중 약 30%의 인원이 핸디를 지원한 적 없다는 것 입니다.
우리는 핸디 지원하기 **버튼의 UI를 변경해 핸디 지원 착오를 줄일 수 있는지 테스트 해보고자 합니다.**
V2 디자인시스템의 색상이 필요해 색상을 직접 지정하여 반영해두었습니다. 
(V1 디자인 시스템 버튼의 색상이 어울리지 않고 안이쁘고 눈에 띄지 않는 이유로 V2에서 현재 사용되는 색상이 필요함.)
https://github.com/user-attachments/assets/a0e630f4-0bae-4b43-be67-113523d41c5b
=> fix: V1 핸디 지원 버튼 디자인 변경 실험

src/app/(home)/@event/components/EventsSwiperView.tsx
캐러셀의 카드 개수를 extend를 할 때 1, 2, 3, 1, 2 로 루프가 돌 수 있던 케이스를 처리했습니다.
=> fix: 캐러셀 카드 extend 로직 수정

src/app/(home)/@event/components/CardSection.tsx, src/app/(home)/@event/components/RecommendedEventCard.tsx, src/app/(home)/@event/components/RecommendedEventSwiperView.tsx, src/app/(home)/@event/components/TrendEventCard.tsx, src/app/(home)/@event/components/TrendEventsSwiperView.tsx, src/services/event.service.ts
- 홈에서 행사 캐러셀 내부의 행사들을 가져올 때 수요조사가 마감된 행사들도 받아오도록 수정했습니다.
- 캐러셀 스크롤 이슈를 해결했습니다.
- 캐러셀 패딩을 피그마 디자인에 맞게 수정했습니다.
=> fix: 홈의 행사 캐러셀 api 조건 수정 및 스크롤 이슈 해결

src/app/event/page.tsx, src/app/event/toSorted.util.ts, src/components/card/Card.tsx
행사 전체보기에서 카드의 값에 실제 데이터를 보여줍니다.
=> fix: 행사 전체보기 페이지에서 목데이터만 표시되는 이슈해결

src/app/mypage/reviews/[reviewId]/components/FilterButton.tsx, src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx, src/app/reviews/components/FilterButton.tsx, src/app/reviews/components/ReviewList.tsx
최신순의 정렬이 반대로 되어있던 걸 고쳤습니다.
https://github.com/user-attachments/assets/f8bc553e-ac25-4a46-b198-e1ea14138159
=> fix: 리뷰 전체보기에서 최신순 정렬 반대로 되어있던 이슈 해결

src/app/event/[eventId]/store/dailyEventIdsWithRoutesAtom.ts
행사 상세 페이지에서 노선들을 불러와 상태관리로 저장하던 값들이 페이지 이동에 따라 초기화 되지 않고 중첩되던 현상을 해결했습니다.
=> hotfix: 행사의 노선이 페이지 이동에 따라 중첩되는 현상 해결

src/app/mypage/reviews/components/WritableReviews.tsx, src/app/mypage/reviews/components/reservation-card/ReviewButton.tsx, src/app/mypage/reviews/write/[reservationId]/page.tsx
작성가능한 후기가 안뜨던 버그 수정, 작성한 후기가 강조표기가 안되던 이슈 해결, 후기 작성하기 재진입 방지 적용
- 작성가능한 후기가 안뜨던 이슈를 해결하였습니다.
- 요약 : 최근 노선의 상태 변경 로직이 변화되어 수정이 필요했습니다. 
- 원인 : 기존 `eventProgressStatus: 'PAST'` 인 행사들을 보여주고 있었습니다. 이는 기존 정책이 행사에 속한 모든 노선이 종료되면 행사의 상태 및 노선의 상태가 ENDED로 변경되어서 가능했던 로직이었습니다. 
- 해결 : 이제 각 노선단위로 ENDED로 변경되기에 `eventProgressStatus: 'PAST'`를 사용하지 않습니다.
- 작성한 후기 - 내 후기 클릭 - 나의 후기가 강조 표기가 안되던 이슈가 해결되었습니다.
- 후기 작성 : 후기를 작성하고 난 뒤, 뒤로가기 등을 사용하여 같은 url에 진입하면 마이페이지 내 후기 목록 페이지로 리디렉트 됩니다.
=> fix: 내 후기 버그 수정 및 피드백 반영

src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx, src/app/event/[eventId]/components/steps/extra-steps/ExtraSidoInfoStep.tsx
행사 상세 보기에서 열린 셔틀 보기를 통해 지역을 선택 했을 시, 수요조사를 요청하면 지역이 처음에 선택한 지역으로 띄워지던 버그를 수정했습니다.
=> fix: 열린 셔틀 보기로 입장 시 수요조사가 다른 지역으로 뜨던 현상 해결

src/app/reservation/[id]/components/PriceStats.tsx, src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx, src/types/shuttleRoute.type.ts
왕복 가격을 마지막 순서로 배치합니다.
타다 상품 셔틀의 도입, 주로 오는편만 이용하는 승객이 대부분. 대형 택시 상품이다보니 상품가가 버스에 비해 높음
버스상품은 왕복가와 편도가가 크게차이나지 않았음. 그러나 택시 상품의 경우 왕복가가 편도상품의 2배 가격임.
주로 오는 편만 예매하는 고객이 대부분임에도, 예약 상세페이지에서 상품 예약을 할때 왕복가가 제일 상단에 먼저 보이면
가격이 비싸보이는 인식을 주게됨. 그래서 왕복가격을 제일 하단으로 순서를 변경하여 편도가를 기준으로 가격을 인지하게 만드려고함.
https://github.com/user-attachments/assets/748b88ce-0fe2-48b3-ab3e-4dc4cf383b1a
=> fix: trip type 순서를 왕복을 마지막으로 변경

src/app/demand/[id]/write/components/JourneyLocationPicker.tsx
v1 프로덕트에서 수요조사시에 [집앞하차] 접두사가 붙은 정류장은 보여주지 않도록 처리합니다.
- 지금은 [집앞하차] 키워드를 가지고 분별하지만, env 값으로 대체할 수도 있습니다. 정류장명이 집앞하차가 아닌, 타다 정류장 등으로 바뀔 수 있다면..
=> fix: 택시 정류장 보여주지 않도록 처리

src/app/(home)/@bot/components/PromotionReviews.tsx, src/app/mypage/reviews/[reviewId]/components/ReviewItem.tsx, src/app/reviews/components/ReviewItem.tsx, src/components/review/FeedbackGroup.tsx, src/components/review/ReviewProperty.tsx, src/types/review.type.ts
00탑승객 | 서비스 만족도 | 탑승 만족도 api 반영되었습니다.
리뷰의 여백 조정되었습니다
- ReviewsViewEntity 에 nullable한 칼럼이 추가되었습니다. toDestinationRegionId, fromDestinationRegionId
- FeedbackGroup 컴포넌트를 분리하였습니다. (이전엔 홈의 리뷰, 마이페이지 내 후기 확인하기, 리뷰 전체보기 3군데서 사용되고 있었음)
- FeedbackGroup 컴포넌트의 네이밍이 ReviewProperty로 변경되었습니다.
=> feat: 리뷰 피드백 텍스트 api 반영

src/app/(home)/@bot/components/PromotionReviews.tsx, src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx, src/app/reviews/components/ReviewList.tsx, src/services/review.service.ts
기존에 리뷰를 조회하고 프론트에서 정렬하던 방식을 api 파라미터로 정렬값을 보내 정렬된 데이터를 받아오는 방식으로 수정했습니다.
이로 페이지네이션 과정에서 정렬이 올바르게 되지 않던 부분을 수정했습니다.
=> fix: 리뷰 조회 시에 정렬 파라미터 적용

src/app/event/[eventId]/components/steps/common-steps/CommonDateStep.tsx
일자별 수요조사 모집 중 버튼 ui및 텍스트 변경
요청사항 : jujeon 준성님 이거 QA할 때 피그마에 넣어놓았던 요청사항인데 반영이 안된 것 같아요..! 
전지역 수요조사 중일 때 수요조사 참여 버튼 변경 요청드려도될까요? 기존 버튼은 버튼보다 태그처럼 보이고 액션 트리거도 잘 안되는 같아서요오 🥲
| 변경전 | 변경후 |
|--------|--------|
| <img width="386" alt="Screenshot 2025-06-17 at 3 46 36 PM" src="https://github.com/user-attachments/assets/7317a41d-3865-4ecf-93ee-a85fff76147d" /> | <img width="409" alt="Screenshot 2025-06-17 at 3 41 18 PM" src="https://github.com/user-attachments/assets/77bf8eb8-3003-4ea4-bba8-0b95839f9fdc" /> | 
=> design: 일자별 수요조사 모집 중 버튼 ui및 텍스트 변경

src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
행사 상세 페이지에서 예약 정류장을 보여주는 단계의 바텀시트에서 수요조사가 가능할 때에만 요청하기 섹션이 보이도록 처리했습니다.
=> hotfix: 예약 정류장 바텀시트에서 수요조사가 열렸을 때에만 요청하기 버튼 표시

src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx, src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
핸디팟 정류장이 수요조사 단게에서 최근에 본 정류장에 뜨지 않도록 수정했습니다.
=> fix: 핸디팟 정류장을 수요조사 단계에서 최근에 본 정류장에 뜨지 않도록 처리

src/app/event/[eventId]/components/steps/common-steps/CommonDateStep.tsx, src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
기존에 시군구 단위로 보여지던 수요조사 수를 숨기고 일자 단위로 보여지도록 수정했습니다.
=> feat: 행사의 수요조사 수를 보여주는 단위 수정

src/app/event/[eventId]/components/shuttle-route-detail-view/components/KakaoMap.tsx
행사 노선 보기에서 [집앞하차] 접두사가 붙은 정류장의 지도를 클릭했을때 404 페이지가 뜨던 이슈를 임시 조치하였습니다.
=> fix: 핸디팟 정류장일때 지도 클릭시 404 페이지 이슈

src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
결제 단계에서 노선 방향에 따라 hub id를 올바르게 처리하여 예약이 생성되도록 수정했습니다.
=> fix: 노선 방향에 따라 hub id 빈 값으로 처리하여 예약 생성

src/app/(home)/@event/components/RecommendedEventCard.tsx, src/app/event/components/FilterBar.tsx, src/app/event/page.tsx, src/components/chips/Chip.tsx, src/constants/status.ts, src/types/event.type.ts
행사 목록 및 캐러셀에 전체 행사 필터 버튼을 추가하고, 스포트 행사 타입을 반영 했습니다.
=> feat: 전체 행사 필터 추가 및 스포츠 타입 반영

src/app/event/page.tsx, src/constants/handyPartyArea.const.ts
핸디팟에서 용인 지역 검색 시 의도대로 지역이 제한되어 검색되지 않던 버그를 해결했습니다.
그 외에 행사 목록 페이지에서 행사 날짜가 하루일 때에도 ~ 표시를 통해 보이던 이슈를 해결했습니다.
=> fix: 용인 지역 주소 검색 제한 상수 수정

src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/ReservationPersonInfoSection.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/CancelBottomSheet.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/RadioInputGroup.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/const/refund.const.ts, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/hooks/useBottomSheetText.ts, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/hooks/useHistory.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/utils/createFeedbackContent.util.ts, src/types/reservation.type.ts
예약 취소 사유 모달을 반영했습니다.
- 예약 내역에 실명 반영 안된 곳 실명 반영
- 셔틀 종료시 예약 취소 불가 처리
- 예약 취소 사유 모달
https://github.com/user-attachments/assets/ee6c59ba-82c5-412f-8e1b-5c0c4ca0a605
| 작성한 예약 취소 사유들은 어드민 - 피드백에서 보실 수 있습니다 |
|--|
|<img width="533" height="183" alt="Screenshot 2025-08-01 at 2 21 05 PM" src="https://github.com/user-attachments/assets/5587ad83-c7ed-42ea-9714-1aa0aa1cced3" />|
선택시 선택 색깔을 바꾸려면 accentColor 스타일을 사용하면 됩니다. 그러나 테두리 색 border 를 수정하려면 appearence:none 을 적용해야하는데요, 이러면 accentColor 스타일을 적용할 수 없습니다. 즉, 선택시 가운데에 색상이 차오르는 효과를 직접 구현해야하는데요, 이를 시도해보았지만 2-3시간안에 처리할 수 없어서 보류하였습니다. 현재는 border 색깔 회색을 포기하고 accentColor 를 회색으로 반영하는 방식으로 간단하게 처리되어있습니다. 
보람님께서는 전혀 티 안난다고 문제없다고 하셨는데 그래도 궁금해져서 혹시 appearence:none 을 적용하고 선택시 가운데 차오르는 커스텀 스타일을 어떻게 만들 수 있는지 아시면 댓글 달아주시면 감사하겠습니다 🙇🏻‍♂️
| figma | 적용된 디자인| …
=> feat: 예약 취소 사유 모달

src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/RadioInputGroup.tsx
기타 input 의 사용성을 개선했습니다.
갑자기 해결방법이 뚝딱 떠올라서 10분안에 개발 및 작성완료하였습니다
- 초기요청 : 기타 라디오 버튼을 클릭하지 않더라도 input을 클릭하면 라디오 버튼이 클릭되고 input 이 disabled->albed로 사용하고 싶음
- 문제점 : raido 버튼과 input을 가진 부모 태그에 onClick 이벤트를 두었으나, input을 클릭해도 라디오 버튼이 선택되지 않음. 추측하건데 disabled 속성을 주면, input의 클릭 이벤트 자체가 발생하지 않아서, 부모태그의 onClick 이벤트 자체가 발동하지 않음.
- 해결방법 : 기타 input의 disabled를 사용하지 않음, 대신 기타를 선택하지 않았을때, css style로 투명도를 줘서 비활성화 된 것처럼 보이게 만듦.
https://github.com/user-attachments/assets/5c0affdc-4645-4dce-bca2-82cd32622d1b
=> fix: 예약 취소 모달 기타 input 사용성 개선

src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
- 예약완료페이지 업데이트
- 유저들은 예약완료페이지에 로딩화면이 있을 수 있습니다. (셔틀버스, 핸디팟 구분, 오픈챗방 링크 데이터 필요)
|셔틀버스 예약완료|핸디팟 예약완료|
|-|-|
|<img width="370" height="669" alt="Screenshot 2025-08-08 at 12 49 15 PM" src="https://github.com/user-attachments/assets/e3fd0c94-1291-40db-9c57-53a10ce98f58" />|<img width="358" height="667" alt="Screenshot 2025-08-08 at 12 49 24 PM" src="https://github.com/user-attachments/assets/e031b1c2-0713-4be7-917c-c0454de48aed" />|
=> feat: 예약완료페이지에 공지방 링크 반영, 핸디팟은 기본 페이지처리

sentry.edge.config.ts, sentry.server.config.ts, src/app/(home)/@greeting/page.tsx, src/app/auth/identity-verification/page.tsx, src/app/auth/login/[oauth]/page.tsx, src/app/error.tsx, src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx, src/app/event/[eventId]/components/shuttle-route-detail-view/components/KakaoMap.tsx, src/app/event/[eventId]/components/steps/components/RequestSeatAlarmButton.tsx, src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx, src/app/event/[eventId]/components/steps/extra-steps/ExtraRealNameInputStep.tsx, src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx, src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/page.tsx, src/app/mypage/alert-requests/components/AlertRequestCard.tsx, src/app/mypage/coupons/components/RegisterCoupon.tsx, src/app/mypage/reviews/edit/[reviewId]/components/ReviewEditForm.tsx, src/app/mypage/reviews/write/[reservationId]/components/ReviewWriteForm.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/CancelBottomSheet.tsx, src/app/not-found.tsx, src/components/feedback/FeedbackScreen.tsx, src/components/kakao-map/KakaoMap.tsx, src/hooks/analytics/useShareTracking.ts, src/hooks/useNotFoundTracking.ts, src/hooks/useTossPayments.tsx, src/instrumentation-client.ts, src/services/config.ts
모든 try catch문에 captureExeption 을 추가하였습니다.
**Tag, Extra**
- tag와 extra 정보를 추가하였는데요, 
tag는 어느 위치에서 발생했는지 sentry 에서 필터링이 가능하고, 
extra는 필터링은 안되지만 발생한 에러와 직접 관련된 정보를 담고 있습니다. 
- extra 정보에 더 많은 데이터를 반영하면 좋지만, 추가적인 api 로직을 반영해야하기 때문에
api 콜 없이 담을 수 있는 정보까지만 반영하였습니다.
- 우선은 임의로 데이터를 반영해두었는데요, 이후 sentry 에러 트래킹에서 필요한 데이터들이 생긴다면
추가 반영해두겠습니다
**Production 환경에서만 init**
- develop, local 환경에서는 sentry가 init 되지 않습니다.
=> feat: 모든 try catch문에 sentry capture exception 추가

src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx, src/app/mypage/boarding-pass/hooks/useBoardingPassData.ts, src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx, src/hooks/useTempSeventeen.ts
외국인 노선인 명동합정 노선 옵챗 추가 및 reservation card 에도 임시 오픈챗 연결을 해두었습니다.
커스텀 훅으로 공통로직으로 처리해두었습니다
=> fix: 명동합정 노선 옵챗 추가 및 reservation card 에도 반영

src/app/mypage/reviews/components/WritableReviews.tsx, src/app/mypage/reviews/components/WrittenReviews.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/HubItem.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/TripCard.tsx, src/components/loading/Loading.tsx
- 핸디팟을 예매한 경우 희망 주소지로 지도 및 로드뷰를 보여주도록 합니다.
- 핸디팟 행사장행일 경우에는 추가 안내 문구를 보여줍니다.
- 귀가행 탑승 장소가 기존에 도착지 정보를 보여주던 것에서 출발지 정보를 보여주도록 변경하였습니다
- 마이페이지 - 후기 페이지에서 로딩 ui 의 여백을 추가하였습니다.
|셔틀버스|핸디팟 행사장행|핸디팟 귀가행|
|-|-|-|
|<img width="352" height="1290" alt="Screenshot 2025-09-18 at 5 26 48 PM" src="https://github.com/user-attachments/assets/0ad92fae-9f1d-45a5-a5ed-103a4539d5d4" />|<img width="367" height="1291" alt="Screenshot 2025-09-18 at 5 27 02 PM" src="https://github.com/user-attachments/assets/2623eba9-e259-472b-adc8-f804944c1fa0" />|<img width="356" height="1293" alt="Screenshot 2025-09-18 at 5 27 22 PM" src="https://github.com/user-attachments/assets/58ffda4a-fcea-4b8c-b484-445c63d98710" />|
=> feat: 예약상세 - 지도 및 로드뷰 미리보기에 핸디팟 케이스 대응, 후기 로딩 ui 여백 추가

src/app/mypage/shuttle/reservation/[reservationId]/components/FirstVisitModal.tsx, src/app/mypage/shuttle/reservation/[reservationId]/page.tsx
예약취소, 셔틀 종료 상태에서는 예약 상세 페이지 모달을 띄워주지 않습니다.
=> feat: 예약취소, 셔틀 종료 상태에서는 예약 상세 페이지 모달 방지

src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx, src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/Roadview.tsx, src/app/mypage/shuttle/reservation/[reservationId]/page.tsx
로드뷰 세로각도(tilt) 반영 및 예약취소/셔틀종료 예약내역에서 모달이 뜨던 이슈 해결되었습니다
- 로드뷰 초기 렌더링시 zoom 을 최대한 멀리 땡겨서 유저들이 탑승장소를 좀 더 잘 인지할 수 있게 변경합니다.
- tilt 값은 고정값에서 어드민에서 설정한 값이 반영되게 변경하였습니다. 초기엔 살짝 하단을 바라보게 설정해두면 대부분의 장소에서도 적절한 시점이라고 판단되어 설정해두었는데요, 모든 정류장에 적절한 값이라고 보기 어려워 어드민에서 추가 설정 및 반영하게 변경해두었습니다.
=> fix: 로드뷰 줌, 세로각도(tilt) 반영 및 예약취소/셔틀종료 예약내역에서 모달이 뜨던 이슈 해결
